### ISSUE TITLE
Bazel@HEAD: Regex passed to `-XepExcludedPaths` to skip generated files from error prone check stopped working

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#19647]
### Description of the bug:

We are seeing breakage with exclusion of files checked by error prone. In 6.3.2 the regex provided to `error-prone` option:  `-XepExcludedPaths:` works as expected:

tools/BUILD
```python
java_package_configuration(
    name = "error_prone",
    javacopts = [
        "-XepDisableWarningsInGeneratedCode",
        # The XepDisableWarningsInGeneratedCode disables only warnings, but
        # not errors. We should manually exclude all files generated by
        # AutoValue; such files always start AutoValue_..., $AutoValue_...,
        # $$AutoValue_... or AutoValueGson_...
        # XepExcludedPaths is a regexp. If you need more paths - use | as
        # separator.
        "-XepExcludedPaths:.*/\\\\$$?\\\\$$?AutoValue(Gson)?_.*\\.java",
[...]
```

On Bazel@HEAD (and already in Pre-Release: 7.0.0-pre.20230917.3) error prone bug pattern violation are reported in generated files, that should be actually excluded from error-prone check:

```bash
  $ bazeldev build java/com/google/gerrit/entities
[...]
ERROR: /home/davido/projects/gerrit2/java/com/google/gerrit/entities/BUILD:7:13: Building java/com/google/gerrit/entities/libentities.jar (79 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor, AutoOneOfProcessor, AutoValueGsonAdapterFactoryProcessor) failed: (Exit 1): java failed: error executing Javac command (from target //java/com/google/gerrit/entities:entities) external/remotejdk17_linux/bin/java '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 19 arguments skipped)
java/com/google/gerrit/entities/LabelType.java:249: warning: [PreferredInterfaceType] Variable type should use the immutable type (such as ImmutableList) instead of the general collection interface type (such as List).
      List<LabelValue> valueList = sortValues(getValues());
          ^
    (see https://errorprone.info/bugpattern/PreferredInterfaceType)
  Did you mean 'ImmutableList<LabelValue> valueList = sortValues(getValues());'?
java/com/google/gerrit/entities/converter/PatchSetProtoConverter.java:48: warning: [PreferredInterfaceType] Variable type should use the immutable type (such as ImmutableList) instead of the general collection interface type (such as List).
    List<String> groups = patchSet.groups();
        ^
    (see https://errorprone.info/bugpattern/PreferredInterfaceType)
  Did you mean 'ImmutableList<String> groups = patchSet.groups();'?
bazel-out/k8-fastbuild/bin/java/com/google/gerrit/entities/_javac/entities/libentities_sources/com/google/gerrit/entities/$AutoValue_GroupReference.java:9: error: [VariableNameSameAsType] Variable named UUID has the type UUID. Calling methods using "UUID.something" are difficult to distinguish between static and instance methods.
  private final AccountGroup.UUID UUID;
                                  ^
    (see https://errorprone.info/bugpattern/VariableNameSameAsType)
bazel-out/k8-fastbuild/bin/java/com/google/gerrit/entities/_javac/entities/libentities_sources/com/google/gerrit/entities/$AutoValue_GroupReference.java:14: error: [VariableNameSameAsType] Variable named UUID has the type UUID. Calling methods using "UUID.something" are difficult to distinguish between static and instance methods.
      @Nullable AccountGroup.UUID UUID,
                                  ^
    (see https://errorprone.info/bugpattern/VariableNameSameAsType)
Target //java/com/google/gerrit/entities:entities failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 28.269s, Critical Path: 28.07s
INFO: 2 processes: 2 internal.
ERROR: Build did NOT complete successfully
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Clone gerrit Code-Review [project](https://gerrit.googlesource.com/gerrit) recursively, and run (with Bazel@HEAD, or with 7.0.0-pre.20230917.3)

```
  $ bazeldev build java/com/google/gerrit/entities
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

Bazel@HEAD or 7.0.0-pre.20230917.3

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

`bazel build src:bazel-bin-dev`

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

e9b2ccc884c831e68d5fc7d46e0cfab24e25e1b4 is the first bad commit.

### Have you found anything relevant by searching the web?

I checked error-prone code related to `-XepExcludedPaths` and have not found any related changes.

### Any other information, logs, or outputs that you want to share?

The regex used is related to https://github.com/google/error-prone/issues/808 .

The reason we do need this regex to exclude generated sources considered by error-prone, is because there are files with different number of  `$`-prefixes generated by `auto-value` libraries:

```
  davido@wizball:~/projects/gerrit (master *>)$ find bazel-out/k8-fastbuild/bin/java/com/google/gerrit/entities/_javac -regex ".*AutoValue.*"
bazel-out/k8-fastbuild/bin/java/com/google/gerrit/entities/_javac/entities/libentities_sources/com/google/gerrit/entities/AutoValue_PermissionRule.java
bazel-out/k8-fastbuild/bin/java/com/google/gerrit/entities/_javac/entities/libentities_sources/com/google/gerrit/entities/AutoValue_AccountGroup_NameKey.java
bazel-out/k8-fastbuild/bin/java/com/google/gerrit/entities/_javac/entities/libentities_sources/com/google/gerrit/entities/AutoValue_SubmitRequirementResult.java
bazel-out/k8-fastbuild/bin/java/com/google/gerrit/entities/_javac/entities/libentities_sources/com/google/gerrit/entities/AutoValue_PatchSetApproval_Key.java
bazel-out/k8-fastbuild/bin/java/com/google/gerrit/entities/_javac/entities/libentities_sources/com/google/gerrit/entities/AutoValue_Account_Id.java
bazel-out/k8-fastbuild/bin/java/com/google/gerrit/entities/_javac/entities/libentities_sources/com/google/gerrit/entities/AutoValue_CachedProjectConfig.java
bazel-out/k8-fastbuild/bin/java/com/google/gerrit/entities/_javac/entities/libentities_sources/com/google/gerrit/entities/$AutoValue_NotifyConfig.java
bazel-out/k8-fastbuild/bin/java/com/google/gerrit/entities/_javac/entities/libentities_sources/com/google/gerrit/entities/AutoValue_BranchNameKey.java
bazel-out/k8-fastbuild/bin/java/com/google/gerrit/entities/_javac/entities/libentities_sources/com/google/gerrit/entities/AutoValue_PatchSet.java
bazel-out/k8-fastbuild/bin/java/com/google/gerrit/entities/_javac/entities/libentities_sources/com/google/gerrit/entities/$$AutoValue_SubmitRequirementResult.java
bazel-out/k8-fastbuild/bin/java/com/google/gerrit/entities/_javac/entities/libentities_sources/com/google/gerrit/entities/AutoValue_Project.java
bazel-out/k8-fastbuild/bin/java/com/google/gerrit/entities/_javac/entities/libentities_sources/com/google/gerrit/entities/$AutoValue_Address.java
```

Workaround is to duplicate the escaping to preserve the back slashes:

```diff
diff --git a/tools/BUILD b/tools/BUILD
index c6149a530c..99f3a07d20 100644
--- a/tools/BUILD
+++ b/tools/BUILD
@@ -50,7 +50,7 @@ java_package_configuration(
         # $$AutoValue_... or AutoValueGson_...
         # XepExcludedPaths is a regexp. If you need more paths - use | as
         # separator.
-        "-XepExcludedPaths:.*/\\\\$$?\\\\$$?AutoValue(Gson)?_.*\\.java",
+        "-XepExcludedPaths:.*/\\\\\\\\$$?\\\\\\\\$$?AutoValue(Gson)?_.*\\.java",
         "-Xep:AlmostJavadoc:ERROR",
         "-Xep:AlreadyChecked:ERROR",
         "-Xep:AlwaysThrows:ERROR",
```

I instrumented the related Bazel code:

```
diff --git a/src/main/starlark/builtins_bzl/common/java/java_common_internal_for_builtins.bzl b/src/main/starlark/builtins_bzl/common/java/java_common_internal_for_builtins.bzl
index 8a7f8464fc..b2b7414014 100644
--- a/src/main/starlark/builtins_bzl/common/java/java_common_internal_for_builtins.bzl
+++ b/src/main/starlark/builtins_bzl/common/java/java_common_internal_for_builtins.bzl
@@ -189,7 +189,9 @@ def compile(
         plugin_info = disable_plugin_info_annotation_processing(plugin_info)
         enable_direct_classpath = False
 
+    print(all_javac_opts)
     all_javac_opts_list = helper.tokenize_javacopts(ctx, all_javac_opts)
+    print(all_javac_opts)
     uses_annotation_processing = False
     if "-processor" in all_javac_opts_list or plugin_info.plugins.processor_classes:
         uses_annotation_processing = True
```

and can confirm that the tokenization is still preserving the regex correctly:

```diff
DEBUG: /virtual_builtins_bzl/common/java/java_common_internal_for_builtins.bzl:192:10: depset(["-source 11 -target 11 -XDskipDuplicateBridges=true -XDcompilePolicy=simple -g -parameters -Xep:ReturnValueIgnored:OFF -Xep:IgnoredPureGetter:OFF -Xep:EmptyTopLevelDeclaration:OFF -Xep:LenientFormatStringValidation:OFF -Xep:ReturnMissingNullable:OFF -Xep:UseCorrectAssertInTests:OFF", "-XepDisableWarningsInGeneratedCode -XepExcludedPaths:.*/\\$?\\$?AutoValue(Gson)?_.*.java 
```

However, if I check the actually regex passed to compiler, the back slash are gone:

cat bazel-out/k8-fastbuild/bin/java/com/google/gerrit/entities/libentities.jar-0.params
```
--javacopts
-source
11
-target
11
-XDskipDuplicateBridges=true
-XDcompilePolicy=simple
-g
-parameters
-Xep:ReturnValueIgnored:OFF
-Xep:IgnoredPureGetter:OFF
-Xep:EmptyTopLevelDeclaration:OFF
-Xep:LenientFormatStringValidation:OFF
-Xep:ReturnMissingNullable:OFF
-Xep:UseCorrectAssertInTests:OFF
-XepDisableWarningsInGeneratedCode
-XepExcludedPaths:.*/$?$?AutoValue(Gson)?_.*.java
```

Previously, the back slashes were preserved:
```
-XepExcludedPaths:.*/\$?\$?AutoValue(Gson)?_.*.java
```

**Comment by davido** [comment]
//CC @hvadehra
