### ISSUE TITLE
process-wrapper-legacy.cc: error: 'PR_SET_CHILD_SUBREAPER' was not declared in this scope

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/bazel#11637]
### Description of the problem / feature request:

I'm unable to compile Bazel 3.3 for CentOS 6.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Get yourself a pre-Linux 3.4 distro.
2. Try to compile Bazel from source.

### What operating system are you running Bazel on?

CentOS 7.7 (targeting CentOS 6; glibc 2.12; kernel 2.6.32)

### What's the output of `bazel info release`?

n/a. This is the 3.3.0 bootstrap build (from bazel-3.3.0-dist.zip).

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

This `PR_SET_CHILD_SUBREAPER` macro was introduced by c6f0f41c8ee8f40b97b1c1c94ca9b75afb02d961 (cc @jmmv).

I don't know what Bazel's minimum supported kernel and glibc versions are, so I don't know if this should actually be fixed in Bazel's sources, or if users of ancient distros are on their own. (CentOS 6 reaches EOL on Nov 30, 2020.) Version requirements (glibc, kernel, compiler/libstdc++) should probably be provided somewhere under https://docs.bazel.build/versions/master/install-compile-source.html.

**Comment by jmmv** [comment]
I think this is a question for @philwo. Do we have to support CentOS 6 out of the box?

**Comment by philwo** [comment]
CentOS 6 is not tested on Bazel's CI, so it's officially not supported. But we can accept patches / make accommodations if they're not too intrusive. The latter is subjective and thus I'd refer back to @jmmv. :)

For example, we could `#define PR_SET_CHILD_SUBREAPER` ourselves ([upstream definition is here](https://github.com/torvalds/linux/blob/b719ae070ee2371c37d846616ef7453ec6811990/tools/include/uapi/linux/prctl.h#L158)) if it's not defined during compilation and then gracefully deal at runtime with the `prctl` failing.

**Comment by jmmv** [comment]
Defining `PR_SET_CHILD_SUBREAPER` ourselves would likely break the new process waiting logic. But we still have the old logic around behind the `wait_fix` checks... so we could keep it indefinitely and enable it once this feature isn't present. Not my preference as I was hoping to delete the old slightly broken logic... but should be an easy change at this point given that it's still present.

**Comment by philwo** [comment]
> Defining `PR_SET_CHILD_SUBREAPER` ourselves would likely break the new process waiting logic

Mhm, why would that break the logic? Wouldn't the `prctl` call then fail at runtime with `EINVAL` when the kernel does not support that feature, so we can detect that and fallback to a simpler logic?

**Comment by jmmv** [comment]
I mean, just defining `PR_SET_CHILD_SUBREAPER` to a random value and making `prctl` fail, *without* having a fallback, wouldn't work because we now take advantage of the subreaper feature to wait for processes.

And if we have a fallback (which we still do), then it seems better to `#ifdef` that code out behind the presence of `PR_SET_CHILD_SUBREAPER` instead of redefining the constant.

**Comment by philwo** [comment]
Ahh, understood.

> it seems better to #ifdef that code out behind the presence of PR_SET_CHILD_SUBREAPER instead of redefining the constant

Depends - is the kernel that builds Bazel the same as the kernel that runs Bazel? I'm not so sure. By defining the constant and branching at runtime, the `process-wrapper` will do the right thing *for the system it runs on*, which seems more useful from a user's point of view compared to doing the right thing for the system it was built on.

**Comment by philwo** [comment]
@beasleyr-vmw I'm pretty sure https://github.com/bazelbuild/bazel/commit/e6dd345c66ab315a5768657b1cf236cfa5d4d1df will fix it, but could you give it a try just in case?

**Comment by beasleyr-vmw** [comment]
Thanks for hopping on this. :) Our internal solution was a bit slapdash, and I agree in hindsight that it's not fit for public consumption. I have a tiny tweak to suggest to e6dd345 (new PR), because I don't think the `prctl` error handling is quite right.
