### ISSUE TITLE
grpc compile error on RHEL 7: TCP_USER_TIMEOUT

### ISSUE THREAD

**Issue by gmishkin** [bazelbuild/bazel#8657]
### Description of the problem / feature request:

Similar to #7890 I am having a problem building Bazel on RHEL 7.1 ppc64le. I looked at the headers on the system and `TCP_USER_TIMEOUT` is not present in `tcp.h` even though the glibc version is 2.17. I downloaded the sources from http://ftp.gnu.org/gnu/glibc/ and it looks like the symbol wasn't defined until 2.18 actually.

I changed that `__GLIBC_PREREQ` check to 2.18 and then Bazel builds successfully but I'm not sure if that's the correct solution so I wanted to open this issue to see if there is some else going on and that 2.17 is actually the right value.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
bazel build  --host_javabase=@local_jdk//:jdk         --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8         --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8     //src:bazel
...
ERROR: /home/geoff.mishkin/bazel/third_party/grpc/BUILD:560:1: C++ compilation of rule '//third_party/grpc:grpc_base_c' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 37 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
third_party/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc: In function 'grpc_error* grpc_set_socket_tcp_user_timeout(int, const grpc_channel_args*, bool)':
third_party/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc:301:42: error: 'TCP_USER_TIMEOUT' was not declared in this scope
     if (0 != setsockopt(fd, IPPROTO_TCP, TCP_USER_TIMEOUT, &timeout,
                                          ^
third_party/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc:306:42: error: 'TCP_USER_TIMEOUT' was not declared in this scope
     if (0 != getsockopt(fd, IPPROTO_TCP, TCP_USER_TIMEOUT, &newval, &len)) {
                                          ^
Target //src:bazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2302.831s, Critical Path: 1281.57s
INFO: 1439 processes: 1 local, 1317 processwrapper-sandbox, 121 worker.
FAILED: Build did NOT complete successfully
```

### What operating system are you running Bazel on?

RHEL 7.1 on PowerPC

### What's the output of `bazel info release`?

`release 0.23.2- (@non-git)`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Bootstrapped on the same machine.

###  Have you found anything relevant by searching the web?

Found #7890 found glibc sources indicating that `TCP_USER_TIMEOUT` was not added til 2.18.

**Comment by emidln** [comment]
This was fixed by an update to grpc. In the meantime, you can hack grpc like this prior to `bazel build`:

```
# Patch bazel's grpc to work on pre-glibc-2.17
sed -i'' 's|<netinet/tcp.h>|<linux/tcp.h>|' third_party/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc
```

**Comment by irengrig** [comment]
If it was fixed by grpc, can I close the issue? Or is it still something with Bazel? Thank you

**Comment by gmishkin** [comment]
I assumed he meant it was fixed in grpc upstream; the copy in bazel still uses the glibc 2.17 check instead which I was thinking should be 2.18.

**Comment by irengrig** [comment]
Thank you for the clarification.

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.
