### ISSUE TITLE
Android Binary undefined reference to `dl_iterate_phdr'

### ISSUE THREAD

**Issue by shamtron** [bazelbuild/bazel#10852]
### Description of the problem / feature request:

Android project no longer builds after upgrading from Bazel 0.23.2 to 2.1.1. 

### Feature requests: what underlying problem are you trying to solve with this feature?

Generate Android binary after upgrading Bazel version.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Only reproducible in private codebase. Able to build the sample Android project. Would like to modify sample project to try to re-create the issue but not sure where to start since error log does not point to a specific file in my codebase.

### What operating system are you running Bazel on?

macOS Catalina

### What's the output of `bazel info release`?

release 2.1.1

###  Have you found anything relevant by searching the web?

From what I've been able to find most recommendations say to add 'ldl' to linkopts. This does not work.

Places to look:
- StackOverflow: https://stackoverflow.com/questions/14324157/undefined-reference-to-dl-iterate-phdr
- GitHub issues: https://github.com/bazelbuild/bazel/issues/10837#issuecomment-589911196

### Any other information, logs, or outputs that you want to share?

Using Android SDK 29.0.2 & build tools 29.0.2
Using Android NDK 17.2 with api level 21

Please see attached log for details:
[crash_log.txt](https://github.com/bazelbuild/bazel/files/4246652/crash_log.txt)

**Comment by jin** [comment]
As discussed in the Slack chat, please share your .bazelrc configurations.

```
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -o bazel-out/arm64-v8a-fastbuild/bin/external/remote_java_tools_linux/ijar_cc_binary bazel-out/arm64-v8a-fastbuild/bin/external/remote_java_tools_linux/_objs/ijar_cc_binary/classfile.pic.o bazel-out/arm64-v8a-fastbuild/bin/external/remote_java_tools_linux/_objs/ijar_cc_binary/ijar.pic.o bazel-out/arm64-v8a-fastbuild/bin/external/remote_java_tools_linux/libzip.a bazel-out/arm64-v8a-fastbuild/bin/external/remote_java_tools_linux/libplatform_utils.a bazel-out/arm64-v8a-fastbuild/bin/external/remote_java_tools_linux/libfilesystem.a bazel-out/arm64-v8a-fastbuild/bin/external/remote_java_tools_linux/liberrors.a bazel-out/arm64-v8a-fastbuild/bin/external/remote_java_tools_linux/libport.a bazel-out/arm64-v8a-fastbuild/bin/external/remote_java_tools_linux/liblogging.a bazel-out/arm64-v8a-fastbuild/bin/external/remote_java_tools_linux/libstrings.a bazel-out/arm64-v8a-fastbuild/bin/external/remote_java_tools_linux/libzlib_client.a bazel-out/arm64-v8a-fastbuild/bin/external/remote_java_tools_linux/java_tools/zlib/libzlib.a external/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++.a external/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_static.a external/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++abi.a -static-libgcc -Wl,-S -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64 -target aarch64-none-linux-android -no-canonical-prefixes -Lexternal/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/arm64-v8a '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm64')
```

It looks like the NDK's clang is being used to compile a host tool, which smells like a bug / bad configuration.

**Comment by shamtron** [comment]
Here is my .bazelrc:

[bazelrc.txt](https://github.com/bazelbuild/bazel/files/4246788/bazelrc.txt)

**Comment by cpsauer** [comment]
Hey @shamtron, to reply to your comments in the other issue: I'm not sure what's wrong, but it looks from your log like -libdl isn't actually getting added as a flag. It's not present in your crash_log.txt.

That's definitely a libdl linker error.  Adding -ldl to the linkopts did the trick for me, as one would expect. Currently, I'm adding it to the linkopts of just the top level cc_library that the android_library depends on. That makes -ldl appear in the call to clang on my computer. (FWIW, I'm using API level 28, for both the SDK and NDK, SDK 28, and NDK 20.1.5948944)

**Comment by jin** [comment]
`build --distinct_host_configuration=false` should be true.

**Comment by shamtron** [comment]
@jin when I set it to true I get:
-> @bazel_tools//tools/jdk:platformclasspath (host)
|   @bazel_tools//tools/jdk:current_java_runtime (host)
|   @bazel_tools//tools/jdk:legacy_current_java_runtime (host)
|   @bazel_tools//tools/jdk:toolchain_hostjdk8 (host)
`-- @bazel_tools//tools/jdk:platformclasspath (host)
This cycle occurred because of a configuration option

**Comment by shamtron** [comment]
I tried a couple of things to help narrow this down:

1. Buidling on Ubuntu. Perhaps it is something about MacOS but turns out I get the same error.
2. Another thing I tried was adding a bogus linker flag. Using 0.23.2 I added a bogus linker flag "-lgarbage" and with that bazel complains that garbage cannot be found; as expected. When I do the same thing on 2.1.1 I get the "undefined reference to `dl_iterate_phdr'" error instead of it complaining about "garbage". 

So perhaps linkopts is being ignorde in 2.1.1 for some reason or it's not being evaluated at the incorrect time?
