### ISSUE TITLE
Bazel not searching /usr/local/include for include files

### ISSUE THREAD

**Issue by yichuan1118** [bazelbuild/bazel#5391]
### Description of the problem / feature request:

Bazel not searching /usr/local/include for header files

zeromq header installed by brew into /user/local/include, building directly using clang works:

`clang cpp/src/bifrost.cc -lzmq`

building using bazel will generate

```
cpp/src/bifrost.h:1:10: fatal error: 'zmq.h' file not found
#include <zmq.h>
         ^~~~~~~
```

Same bazel build works on Linux (ubuntu 18.04) after `sudo apt install libzmq3-dev`

### What operating system are you running Bazel on?

osx 10.13.2

### What's the output of `bazel info release`?

release 0.14.1-homebrew

### Any other information, logs, or outputs that you want to share?

clang search path includes /usr/local/include.
How is bazel detecting include path?

```
⟩ clang -E -xc++ -v /dev/null
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.13.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name null -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 351.8 -v -dwarf-column-info -debugger-tuning=lldb -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0 -stdlib=libc++ -fdeprecated-macro -fdebug-compilation-dir /Users/yichuan/Downloads/zeromq-4.2.5 -ferror-limit 19 -fmessage-length 179 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.13.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o - -x c++ /dev/null
clang -cc1 version 9.1.0 (clang-902.0.39.1) default target x86_64-apple-darwin17.3.0
ignoring nonexistent directory "/usr/include/c++/v1"
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
# 1 "/dev/null"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 353 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "/dev/null" 2
```

**Comment by laszlocsomor** [comment]
Bazel requires that C++ build rules declare all header files that the sources depend on. Only exceptions are the "default" header files, such as POSIX system headers (e.g. `stdio.h`) and STL (e.g. `<iostream>`) -- they are needed so frequently that Bazel doesn't require you to declare them.

I think the culprit is that though `zmq.h` is next to the system headers, Bazel probably doesn't consider it to be a default system header, so you'd need to declare a dependency on it.

/cc @mhlopko : Is my analysis correct? What can @yichuan1118 do to alleviate this problem?

**Comment by laszlocsomor** [comment]
Also, this is not a Bazel bug, so I'll close this issue.

@yichuan1118 : please use [StackOverflow](https://stackoverflow.com/questions/tagged/bazel) or on bazel-discuss@googlegroups.com to ask questions about failing builds.

**Comment by yichuan1118** [comment]
@laszlocsomor @mhlopko Thank you for the answer, please let me know if this is the correct understanding.

**Comment by laszlocsomor** [comment]
> The reason I have some doubts is that the same bazel project works on Linux, which means if there is some "whitelist" for system headers, it is different on Mac and Linux.

Yes, that's indeed strange. Let me reopen because that sounds fishy indeed.

**Comment by mhlopko** [comment]
Hmm this is weird. Bazel is calling clang, so it should use it's include directories right? We actually do run `clang -E -xc++ -v` to get a list of include directories for include validation. Do you have Xcode installed? Can you run your build with `--subcommands` and see what command bazel executes and then pinpoint what's wrong with the command line?

**Comment by mhlopko** [comment]
Did you by chance upgrade your clang recently? Can you repro after `bazel build --expunge`?

**Comment by laszlocsomor** [comment]
You mean `bazel clean --expunge`?

**Comment by mhlopko** [comment]
Indeed I do. Sorry for misbehaving fingers :)

**Comment by yichuan1118** [comment]
@mhlopko 

Unfortunately `bazel clean --expunge` did not help. On my mac 10.13.2 running 
```
⟩ clang -E -xc++ -v
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
which seems do not have the include directory info, I can only get include directory info with
`⟩ clang -E -xc++ -v /dev/null`

with `bazel build -s ` I got the following output:


```
⟩ bazel build -s cpp/src:test_lib
INFO: Analysed target //cpp/src:test_lib (0 packages loaded).
INFO: Found 1 target...
SUBCOMMAND: # //cpp/src:test_lib [action 'Compiling cpp/src/test.cc']
(cd /private/var/tmp/_bazel_yichuan/7121d0bf3c2f72ffb23f9de00287077e/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM='' \
    APPLE_SDK_VERSION_OVERRIDE='' \
    PATH=/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \
    XCODE_VERSION_OVERRIDE=9.3.0 \
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' -iquote . -iquote bazel-out/darwin-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/darwin-fastbuild/genfiles/external/bazel_tools -MD -MF bazel-out/darwin-fastbuild/bin/cpp/src/_objs/test_lib/cpp/src/test.d '-frandom-seed=bazel-out/darwin-fastbuild/bin/cpp/src/_objs/test_lib/cpp/src/test.o' '-isysroot __BAZEL_XCODE_SDKROOT__' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c cpp/src/test.cc -o bazel-out/darwin-fastbuild/bin/cpp/src/_objs/test_lib/cpp/src/test.o)
ERROR: /Users/yichuan/Dropbox/test/cpp/src/BUILD:26:1: C++ compilation of rule '//cpp/src:test_lib' failed (Exit 1)
In file included from cpp/src/test.cc:1:
cpp/src/test.h:3:10: fatal error: 'zmq.h' file not found
#include <zmq.h>
         ^~~~~~~
1 error generated.
Target //cpp/src:test_lib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.499s, Critical Path: 0.32s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by mhlopko** [comment]
The correct command is `clang -E -xc++ - -v` (one extra -). Could you try that please?

**Comment by yichuan1118** [comment]
Running this command does return the correctly search paths, but it seems this command does not return, I need to `ctrl-c` out of it.

```
⟩ clang -E -xc++ - -v
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.13.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 351.8 -v -dwarf-column-info -debugger-tuning=lldb -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0 -stdlib=libc++ -fdeprecated-macro -fdebug-compilation-dir /Users/yichuan/repo/bifrost -ferror-limit 19 -fmessage-length 135 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.13.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o - -x c++ -
clang -cc1 version 9.1.0 (clang-902.0.39.2) default target x86_64-apple-darwin17.6.0
ignoring nonexistent directory "/usr/include/c++/v1"
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
```

**Comment by formath** [comment]
Any progress? I have a same question.
```https://stackoverflow.com/questions/58908156/system-include-path-not-found-when-using-bazel-build```

**Comment by DavidGoldman** [comment]
For anyone still seeing this issue:

* Please run `blaze clean --expunge && bazel build -s --verbose_failures` and include the entire failing action
* Please try running the failed action manually but adding the following to the env part of the command: `__WRAPPED_CLANG_LOG_ONLY=1`. This should make the command print out the resolved arguments to clang.

e.g.
```
...
exec env - \
    APPLE_SDK_PLATFORM='<something>' \
    APPLE_SDK_VERSION_OVERRIDE='<something>' \
    PATH='<something>'  \
    XCODE_VERSION_OVERRIDE='<something>'  \
    __WRAPPED_CLANG_LOG_ONLY='1' \
  external/local_config_cc/wrapped_clang
...
```

**Comment by firstprayer** [comment]
Still reproduce:


```
Taiyuans-MacBook-Pro:faiss_server taiyuanz$ bazel build server:test_faiss -s --verbose_failures
INFO: Analyzed target //server:test_faiss (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
SUBCOMMAND: # //server:test_faiss [action 'Compiling server/TestFaiss.cc', configuration: 18cfe57020ba0967585f86bef0d4debaad436ce580b4a2000cc24e9833cad3f3]
(cd /private/var/tmp/_bazel_taiyuanz/14be20721d2d41866eb3de4329fbf92b/execroot/faiss_server && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.15 \
    PATH=/Users/taiyuanz/Downloads/google-cloud-sdk/bin:/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/opt/X11/bin:/Users/taiyuanz/.rvm/bin:/Users/taiyuanz/local/gradle-3.0/bin:/usr/local/sbin \
    XCODE_VERSION_OVERRIDE=11.3.1.11C504 \
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' -iquote . -iquote bazel-out/darwin-fastbuild/bin -iquote external/bazel_tools -iquote bazel-out/darwin-fastbuild/bin/external/bazel_tools -MD -MF bazel-out/darwin-fastbuild/bin/server/_objs/test_faiss/TestFaiss.d '-frandom-seed=bazel-out/darwin-fastbuild/bin/server/_objs/test_faiss/TestFaiss.o' -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks '-mmacosx-version-min=10.15' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c server/TestFaiss.cc -o bazel-out/darwin-fastbuild/bin/server/_objs/test_faiss/TestFaiss.o)
ERROR: /Users/taiyuanz/Projects/faiss_server/server/BUILD:1:1: C++ compilation of rule '//server:test_faiss' failed (Exit 1) wrapped_clang failed: error executing command
  (cd /private/var/tmp/_bazel_taiyuanz/14be20721d2d41866eb3de4329fbf92b/sandbox/darwin-sandbox/6/execroot/faiss_server && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.15 \
    PATH=/Users/taiyuanz/Downloads/google-cloud-sdk/bin:/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/opt/X11/bin:/Users/taiyuanz/.rvm/bin:/Users/taiyuanz/local/gradle-3.0/bin:/usr/local/sbin \
    XCODE_VERSION_OVERRIDE=11.3.1.11C504 \
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' -iquote . -iquote bazel-out/darwin-fastbuild/bin -iquote external/bazel_tools -iquote bazel-out/darwin-fastbuild/bin/external/bazel_tools -MD -MF bazel-out/darwin-fastbuild/bin/server/_objs/test_faiss/TestFaiss.d '-frandom-seed=bazel-out/darwin-fastbuild/bin/server/_objs/test_faiss/TestFaiss.o' -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks '-mmacosx-version-min=10.15' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c server/TestFaiss.cc -o bazel-out/darwin-fastbuild/bin/server/_objs/test_faiss/TestFaiss.o)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
server/TestFaiss.cc:25:10: fatal error: 'faiss/IndexFlat.h' file not found
#include <faiss/IndexFlat.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

I was trying to run the command manually but I got the following error:
```
Taiyuans-MacBook-Pro:faiss_server taiyuanz$ external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' -iquote . -iquote bazel-out/darwin-fastbuild/bin -iquote external/bazel_tools -iquote bazel-out/darwin-fastbuild/bin/external/bazel_tools -MD -MF bazel-out/darwin-fastbuild/bin/server/_objs/test_faiss/TestFaiss.d '-frandom-seed=bazel-out/darwin-fastbuild/bin/server/_objs/test_faiss/TestFaiss.o' -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks '-mmacosx-version-min=10.15' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c server/TestFaiss.cc -o bazel-out/darwin-fastbuild/bin/server/_objs/test_faiss/TestFaiss.o
Error: DEVELOPER_DIR not set.
Abort trap: 6
```

**Comment by firstprayer** [comment]
Did a little more investigation - in the build directory I checked

```
# vi external/local_config_cc/builtin_include_directory_paths

1 This file is generated by cc_configure and contains builtin include directories
  2 that /private/var/tmp/_bazel_taiyuanz/14be20721d2d41866eb3de4329fbf92b/external/local_config_cc/wrapped_clang reported. This file is a dependency of every compilation action and
  3 changes to it will be reflected in the action cache key. When some of these
  4 paths change, Bazel will make sure to rerun the action, even though none of
  5 declared action inputs or the action commandline changes.
  6
  7 /Applications/Xcode.app/Contents/Developer
  8 /Applications/
```

It looks like it doesn't include the /usr/local/ directory. Wonder if this issue is due to misconfiguration of the cc_configure?

**Comment by firstprayer** [comment]
cc @DavidGoldman any idea based on my description above?

**Comment by lightyang** [comment]
The presence of SDKROOT / isysroot excludes /usr/local/include from the include paths

```
SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk clang -E -xc++ - -v
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1"
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx11.0.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -Werror=implicit-function-declaration -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model pic -pic-level 2 -mthread-model posix -mframe-pointer=all -fno-strict-return -masm-verbose -munwind-tables -target-sdk-version=11.1 -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -target-linker-version 609.8 -v -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -stdlib=libc++ -internal-isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1 -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include -internal-isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -internal-externc-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -internal-externc-isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-final-dtor-non-final-class -Wno-extra-semi-stmt -Wno-misleading-indentation -Wno-quoted-include-in-framework-header -Wno-implicit-fallthrough -Wno-enum-enum-conversion -Wno-enum-float-conversion -fdeprecated-macro -fdebug-compilation-dir /Users/light/projects/quant/sexpr -ferror-limit 19 -fmessage-length 178 -stack-protector 1 -fstack-check -mdarwin-stkchk-strong-link -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fobjc-runtime=macosx-11.0.0 -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o - -x c++ -
clang -cc1 version 12.0.0 (clang-1200.0.32.28) default target x86_64-apple-darwin20.2.0
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
```

**Comment by liuliu** [comment]
@lightyang given that is the root cause, any suggestions to workaround this (if we know what we are doing) with the default toolchain?
