### ISSUE TITLE
Linux, Android, regression: example hello_world project can't build with Bazel 0.5.3

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3514]
### Description of the problem / feature request / question:

In a clean checkout at 05f563a97581959db5da0cb02daf87cfa20c6b88 + WORKSPACE edits (see below), I can't build `//examples/android/java/bazel:hello_world` with Bazel 0.5.3 on Linux. It works with 0.5.2 though.

### If possible, provide a minimal example to reproduce the problem:

I added the android repo rules to my WORKSPACE.
```
  $ git d
diff --git a/WORKSPACE b/WORKSPACE
index a86ba4e6b..7843f369d 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -46,8 +46,19 @@ pull_images_for_docker_tests()
 #   2. Set the $ANDROID_HOME and $ANDROID_NDK_HOME environment variables
 #   3. Uncomment the two lines below
 #
-# android_sdk_repository(name = "androidsdk")
-# android_ndk_repository(name = "androidndk")
+
+android_sdk_repository(
+    name = "androidsdk",
+    path = "(...)/Android/Sdk",
+    api_level = 26,
+    build_tools_version = "26.0.1",
+)
+
+android_ndk_repository(
+    name = "androidndk",
+    path = "(...)/Android/android-ndk-r15",
+    api_level = 26,
+)
 
 # In order to run //src/test/shell/bazel:maven_skylark_test, follow the
 # instructions above for the Android integration tests and uncomment the
```

```
  $ bazel build //examples/android/java/bazel:hello_world 
.....................
(09:11:39) INFO: Current date is 2017-08-07
(...)
Building external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/libdexer.jar (11 source files) failed: Worker process sent response with exit code: 1.
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexBuilder.java:20: error: cannot find symbol
import com.android.dx.command.DxConsole;
                             ^
  symbol:   class DxConsole
  location: package com.android.dx.command
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:18: error: cannot find symbol
import com.android.dx.command.DxConsole;
                             ^
  symbol:   class DxConsole
  location: package com.android.dx.command
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileMerger.java:22: error: cannot find symbol
import com.android.dx.command.DxConsole;
                             ^
  symbol:   class DxConsole
  location: package com.android.dx.command
Target //examples/android/java/bazel:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
(09:12:48) INFO: Elapsed time: 70.534s, Critical Path: 5.25s
(09:12:48) FAILED: Build did NOT complete successfully
```

### Environment info
* Operating System: Ubuntu 14.04 (Trusty)

* Bazel version (output of `bazel info release`): 0.5.3

**Comment by laszlocsomor** [comment]
Culprit is cbee79a2b742886d950d271db59ddfa6c903e0bf

**Comment by laszlocsomor** [comment]
This bug went undetected for more than a month! Apparently we don't have test coverage for the example Android app :(

**Comment by laszlocsomor** [comment]
Building with `--noincremental_dexing` works around the problem.

**Comment by aj-michael** [comment]
This has not been broken for a month. This is #3469 caused by build-tools 26.0.1 which was not released at the time that bazel 0.5.3 was released.

The error your are seeing was fixed in ce61d63. Bazel at HEAD only supports build-tools 26.0.1 and later as of 5393a49 so I updated our CI to install 26.0.1 in https://github.com/bazelbuild/continuous-integration/commit/18fc73a42ebff6b5f6d24b5c0390e0e3318a6884 last Friday.

**Comment by aj-michael** [comment]
As I stated on #3469, this was not really a regression. At the time of bazel 0.5.3 release, bazel worked with the latest build-tools. However build-tools 26.0.1 took us by surprise and rearranged some internal APIs.

**Comment by aj-michael** [comment]
Also, to address the point about coverage: We do build the android sample app on CI, however it does not download the latest build-tools so it will not find breaking changes in android releases. I have an internal bug (64155221) to get test coverage on upcoming build-tools releases.

**Comment by laszlocsomor** [comment]
Thanks! All of that sounds good. I'll use 0.5.4rc2 or custom bazel for now.
