### PR TITLE
Switch to -fdebug-compilation-dir

### PR DESCRIPTION
**Pull request by keith**
This removes some argument parsing from wrapped_clang. This flag was
introduced in clang 9.

### CODE REVIEW

**Review by oquenchil — APPROVED** [review]
LGTM

**Comment by soonho-tri** [comment]
@keith , I'm afraid that this commit causes a compilation error in macOS-14:

 - AFAIK, the latest Xcode we can use in macOS-14 is Xcode 11.2.1. It ships Apple clang version 11.0.0 (clang-1100.0.33.12).
 - Apple clang version 11.0.0 (clang-1100.0.33.12) corresponds to LLVM clang-8.0.0 (see [here](https://en.wikipedia.org/wiki/Xcode#Xcode_7.0_-_12.x_(since_Free_On-Device_Development))).

I think it explains the CI failure in https://github.com/Homebrew/homebrew-core/pull/69466 (bump to bazel-4.0.0)

```
ERROR: /private/tmp/bazel-20210121-22298-3itmz5/sources/third_party/ijar/BUILD:72:10: Compiling third_party/ijar/zip_main.cc failed: (Exit 1): wrapped_clang failed: error executing command 
  (cd /private/tmp/bazel_9Po2zcX3/out/execroot/io_bazel && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.15 \
    PATH=/usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/python@3.9/bin:/usr/local/opt/openjdk@11/bin:/usr/bin:/bin:/usr/sbin:/sbin \
    XCODE_VERSION_OVERRIDE=11.3.1.11C504 \
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG '-DNS_BLOCK_ASSERTIONS=1' '-std=c++11' -fdebug-compilation-dir . -iquote . -iquote bazel-out/darwin-opt/bin -iquote external/bazel_tools -iquote bazel-out/darwin-opt/bin/external/bazel_tools -isystem third_party/zlib -isystem bazel-out/darwin-opt/bin/third_party/zlib -MD -MF bazel-out/darwin-opt/bin/third_party/ijar/_objs/zipper/zip_main.d -DBLAZE_OPENSOURCE '-frandom-seed=bazel-out/darwin-opt/bin/third_party/ijar/_objs/zipper/zip_main.o' -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks '-mmacosx-version-min=10.15' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c third_party/ijar/zip_main.cc -o bazel-out/darwin-opt/bin/third_party/ijar/_objs/zipper/zip_main.o)
Execution platform: //:default_host_platform
[21 / 75] 3 actions running
    Executing genrule //src/tools/xcode/realpath:realpath_genrule; 0s local
    Executing genrule //.../xcode/stdredirect:stdredirect_genrule; 0s local
    Compiling third_party/ijar/zip.cc; 0s local

clang: error: unknown argument: '-fdebug-compilation-dir'
```

**Comment by keith** [comment]
Sorry for the trouble, thanks for the report! here's a revert https://github.com/bazelbuild/bazel/pull/12882

**Comment by soonho-tri** [comment]
Thanks for the update!
