### ISSUE TITLE
Fails to build on i386 (FreeBSD 10.3): portable_sysctlbyname signature mismatch

### ISSUE THREAD

**Issue by yurivict** [bazelbuild/bazel#1318]
```
src/main/native/unix_jni.cc:867:7: error: no matching function for call to 'portable_sysctlbyname'
  if (portable_sysctlbyname(name_chars, &r, &len) == -1) {
      ^~~~~~~~~~~~~~~~~~~~~
./src/main/native/unix_jni.h:95:5: note: candidate function not viable: no known conversion from 'jlong *' (aka 'long long *') to 'long *' for 2nd argument
int portable_sysctlbyname(const char *name_chars, long *mibp, size_t *sizep);
    ^
1 error generated.
Target //src:bazel failed to build
```

**Comment by dslomov** [comment]
@aehlig could you help triage this?

**Comment by kchodorow** [comment]
https://github.com/bazelbuild/bazel/commit/0c19d6223d73f23558a279d91db49fe09e6f36b4

**Comment by aehlig** [comment]
I believe @hermione521's patch 0c19d6223d73f23558a279d91db49fe09e6f36b4 resolved the issue. Feel free to reopen, if the problem persists.
