### PR TITLE
Condition out `PR_SET_CHILD_SUBREAPER` on older Linuxes

### LINKED ISSUE #11637: process-wrapper-legacy.cc: error: 'PR_SET_CHILD_SUBREAPER' was not declared in this scope
### Description of the problem / feature request:

I'm unable to compile Bazel 3.3 for CentOS 6.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Get yourself a pre-Linux 3.4 distro.
2. Try to compile Bazel from source.

### What operating system are you running Bazel on?

CentOS 7.7 (targeting CentOS 6; glibc 2.12; kernel 2.6.32)

### What's the output of `bazel info release`?

n/a. This is the 3.3.0 bootstrap build (from bazel-3.3.0-dist.zip).

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

This `PR_SET_CHILD_SUBREAPER` macro was introduced by c6f0f41c8ee8f40b97b1c1c94ca9b75afb02d961 (cc @jmmv).

I don't know what Bazel's minimum supported kernel and glibc versions are, so I don't know if this should actually be fixed in Bazel's sources, or if users of ancient distros are on their own. (CentOS 6 reaches EOL on Nov 30, 2020.) Version requirements (glibc, kernel, compiler/libstdc++) should probably be provided somewhere under https://docs.bazel.build/versions/master/install-compile-source.html.

### PR DESCRIPTION
**Pull request by beasleyr-vmw**
Commit c6f0f41c8ee8f40b97b1c1c94ca9b75afb02d961 introduced a compile-time
dependency on Linux kernel 3.4 or later via the `PR_SET_CHILD_SUBREAPER`
macro.  Work our way around this by guarding the `wait_fix` option inside
a `LINUX_VERSION_CODE >= KERNEL_VERSION(3,4,0)` check.

Not sure if this will be accepted upstream, but figured it wouldn't hurt to
put it out there.

Resolves #11637.

Testing Done:
- Built Bazel 3.3.0 w/ a modified version of this patch w/ Linux kernel
  headers for 3.0.27.
- `bazelisk test src/test/shell/integration:process_wrapper_test`

### CODE REVIEW

**Comment by beasleyr-vmw** [comment]
I agree w/ @philwo and will amend the PR.
