### ISSUE TITLE
undefined reference to '__atomic_store_8' when building Bazel 3.4.0 on ARM

### ISSUE THREAD

**Issue by koenvervloesem** [bazelbuild/bazel#11757]
### Description of the problem / feature request:

When I build Bazel 3.4.0 on ARM (Raspberry Pi with Raspbian Buster for ARMv7), I get the following error in the "Building Bazel with Bazel." phase.:

```
undefined reference to '__atomic_store_8'
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build Bazel on Raspbian Buster for ARMv7 with the following command:

```shell
env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
```

### What operating system are you running Bazel on?

Raspbian GNU/Linux 10 (buster)

###  Have you found anything relevant by searching the web?

I found this [Japanese blog](https://dev.classmethod.jp/articles/mediapipe-install-on-raspberry-pi-4-with-cpu-gpu/). I don't read Japanese, but this pointed me to the solution: linking against libatomic.

### Any other information, logs, or outputs that you want to share?

[This patch](https://github.com/koenvervloesem/bazel-on-arm/blob/v3.4.0/patches/bazel-3.4.0-arm.patch) solved the problem for me. I don't know if this is the right file to add the linker options, but it works for me: I tested this by building [TensorFlow Addons on ARM](https://github.com/koenvervloesem/tensorflow-addons-on-arm).

**Comment by laurentlb** [comment]
Was the problem caused by the new Bazel release? Did it work with Bazel 3.3?

**Comment by koenvervloesem** [comment]
Yes, Bazel 3.3.1 worked fine with [only the jni_md.h patch](https://github.com/koenvervloesem/bazel-on-arm/blob/master/patches/bazel-3.3.1-arm.patch), so it seems to be caused by the new release. It's a [known problem](https://qengineering.eu/install-tensorflow-2.1.0-on-raspberry-pi-4.html) with other projects such as TensorFlow that libatomic has to be linked against on Raspbian, so the linking should probably become conditional on the platform.

**Comment by laurentlb** [comment]
cc @meisterT

**Comment by meisterT** [comment]
cc @philwo

What is our current policy wrt ARM?

**Comment by philwo** [comment]
@meisterT We’re just getting started with ARM support and I haven’t had time to test on a Raspberry Pi with 32-bit Raspbian yet. I’d be happy to look into getting all the patches in to support it out of the box.

ARM64 Linux should already work fine.
