### ISSUE TITLE
Cannot compile bazel from source

### ISSUE THREAD

**Issue by paladine** [bazelbuild/bazel#735]
After a git pull, building will not work.

src/main/java/com/google/devtools/build/lib/server/signal/InterruptSignalHandler.java:19: warning: Signal is internal proprietary API and may be removed in a future release
import sun.misc.Signal;
               ^
src/main/java/com/google/devtools/build/lib/server/signal/InterruptSignalHandler.java:20: warning: SignalHandler is internal proprietary API and may be removed in a future release
import sun.misc.SignalHandler;
               ^
src/main/java/com/google/devtools/build/lib/server/signal/InterruptSignalHandler.java:19: warning: Signal is internal proprietary API and may be removed in a future release
import sun.misc.Signal;
               ^
src/main/java/com/google/devtools/build/lib/server/signal/InterruptSignalHandler.java:20: warning: SignalHandler is internal proprietary API and may be removed in a future release
import sun.misc.SignalHandler;
               ^
src/main/java/com/google/devtools/build/lib/server/signal/InterruptSignalHandler.java:19: warning: Signal is internal proprietary API and may be removed in a future release
import sun.misc.Signal;
               ^
src/main/java/com/google/devtools/build/lib/server/signal/InterruptSignalHandler.java:20: warning: SignalHandler is internal proprietary API and may be removed in a future release
import sun.misc.SignalHandler;
               ^
src/main/java/com/google/devtools/build/lib/rules/objc/ReleaseBundlingSupport.java:61: error: package com.dd.plist does not exist
import com.dd.plist.NSArray;
                   ^
src/main/java/com/google/devtools/build/lib/rules/objc/ReleaseBundlingSupport.java:62: error: package com.dd.plist does not exist
import com.dd.plist.NSDictionary;
                   ^
src/main/java/com/google/devtools/build/lib/rules/objc/ReleaseBundlingSupport.java:63: error: package com.dd.plist does not exist
import com.dd.plist.NSObject;
                   ^
src/main/java/com/google/devtools/build/lib/rules/objc/ReleaseBundlingSupport.java:410: error: cannot find symbol
  private NSDictionary automaticEntries() {
          ^
  symbol:   class NSDictionary
  location: class ReleaseBundlingSupport
4 errors
6 warnings

**Comment by dslomov** [comment]
This looks like the offending commit: https://github.com/bazelbuild/bazel/commit/d46f474733b048d9ef10dd13ec639b4521693d0a
