### ISSUE TITLE
process-tools-darwin.cc: use of undeclared identifier 'EXIT_FAILURE'

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/bazel#11640]
### Description of the problem / feature request:

Unable to bootstrap Bazel 3.3 on macOS 10.15 (Catalina) using Xcode 10.

```console
Execution platform: //:default_host_platform                                                                                                                                                                                               
src/main/tools/process-tools-darwin.cc:48:5: error: use of undeclared identifier 'EXIT_FAILURE'                                                                                                                                            
    DIE("Expected only one event from the kevent call; got %d", nev);                                                                                                                                                                      
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Attempt to bootstrap Bazel on a macOS 10.15 host configured with Xcode 10.

### What operating system are you running Bazel on?

macOS 10.15 (Catalina) and macOS 10.12 (Sierra)

### What's the output of `bazel info release`?

n/a; bootstrapping

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

This was introduced by b07b799cdf2 (cc @jmmv).

`EXIT_SUCCESS` and `EXIT_FAILURE` come from stdlib.h. The compiler error may be addressed by including stdlib.h from either src/main/tools/process-tools-darwin.cc or src/main/tools/logging.h. I'm not sure which is preferable to the Bazel authors.
