### ISSUE TITLE
New exit code for remote cache errors

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#16513]
### Description of the feature request:

It would be better if Bazel can have a different exit code for remote cache errors. Currently:

* cache misses in build without the bytes returns 1: https://github.com/bazelbuild/bazel/blob/e7218d556a2a265183a10a19fcaa21c0277820ad/src/main/java/com/google/devtools/build/lib/remote/RemoteActionInputFetcher.java#L99
* remote cache time out returns 36 with message "I/O exception during sandboxed execution: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded"

### What underlying problem are you trying to solve with this feature?

Remote cache errors can often be fixed after retrying, maybe with slightly different Bazel flags such as cache misses in Build without the bytes. However, regular build errors such as compilation error cannot be fixed by retrying. Having a separate exit code for remote cache errors allow our CI to easily detect them and retry.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 5.3.1

**Comment by tjgq** [comment]
Yes, this should probably be an exit code 34 (REMOTE_ERROR): https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/util/ExitCode.java;l=60;drc=00bd2910bf76df9a10d7fff466fab6485ad71cbe

**Comment by coeuvre** [comment]
New exit code 39 was introduced by #17358.
