### ISSUE TITLE
CI, protobuf: failing with bazel 0.9.0 rc2

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4250]
**Blocking: https://github.com/bazelbuild/bazel/issues/3773**

Log: https://ci.bazel.io/job/Global/job/protobuf/311/console

Ran as part of Bazel 0.9.0 rc2 test: https://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/release/533/Downstream_projects/

Binaries: https://releases.bazel.build/0.9.0/rc2/index.html

Example log:
```
[variation=,node=ubuntu_16.04-x86_64] ERROR: /home/ci/workspace/Global/protobuf-variation=,node=ubuntu_16.04-x86_64/BUILD:498:1: Couldn't build file protobuf_test: Linking of rule '//:protobuf_test' failed (Exit 1): gcc failed: error executing command 
[variation=,node=ubuntu_16.04-x86_64]   (cd /home/ci/.cache/bazel/_bazel_ci/e31f63748e77b7289938e8c5a89449c0/execroot/com_google_protobuf && \
[variation=,node=ubuntu_16.04-x86_64]   exec env - \
[variation=,node=ubuntu_16.04-x86_64]     PATH=/home/ci/node/node-v6.9.1-linux-x64/bin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin \
[variation=,node=ubuntu_16.04-x86_64]     PWD=/proc/self/cwd \
[variation=,node=ubuntu_16.04-x86_64]   /usr/bin/gcc -o bazel-out/k8-fastbuild/bin/protobuf_test '-Wl,-rpath,$ORIGIN/_solib_k8/' -Lbazel-out/k8-fastbuild/bin/_solib_k8 -pthread -pthread '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,-S -Wl,@bazel-out/k8-fastbuild/bin/protobuf_test-2.params)
[variation=,node=ubuntu_16.04-x86_64] 
[variation=,node=ubuntu_16.04-x86_64] Use --sandbox_debug to see verbose messages from the sandbox
[variation=,node=ubuntu_16.04-x86_64] bazel-out/k8-fastbuild/bin/_solib_k8/liblibprotobuf_Ulite.so: error: undefined reference to 'vtable for google::protobuf::internal::ImplicitWeakMessage'
[variation=,node=ubuntu_16.04-x86_64] /usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
[variation=,node=ubuntu_16.04-x86_64] bazel-out/k8-fastbuild/bin/_solib_k8/liblibprotobuf_Ulite.so: error: undefined reference to 'typeinfo for google::protobuf::internal::ImplicitWeakMessage'
[variation=,node=ubuntu_16.04-x86_64] bazel-out/k8-fastbuild/bin/_objs/protobuf_test/src/google/protobuf/testing/googletest.pic.o:googletest.cc:function google::protobuf::(anonymous namespace)::GetTemporaryDirectoryName(): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
[variation=,node=ubuntu_16.04-x86_64] collect2: error: ld returned 1 exit status
[variation=,node=ubuntu_16.04-x86_64] INFO: Elapsed time: 112.723s, Critical Path: 36.45s
[variation=,node=ubuntu_16.04-x86_64] FAILED: Build did NOT complete successfully
```

**Comment by laszlocsomor** [comment]
TODO:
- repro the failure with Bazel 0.9.0 rc2
- try to repro with Bazel 0.8.1, see if it's failing with that too
  - if failing, then mark as non-blocker for #3773 
  - if not failing, bisect commits to find culprit

**Comment by dslomov** [comment]
Already fails with 0.8.0rc5 (I just happen to have it on my machine so could check quickly).
Checking with 0.8.1 now

**Comment by dslomov** [comment]
for 0.8.1, `bazel build //:protobuf_test` fails with the same error

**Comment by dslomov** [comment]
Bisected to https://github.com/google/protobuf/commits/92a7e778e7394386f413cec28d67a07630f784b1

**Comment by laszlocsomor** [comment]
thanks! /cc @acozzette

**Comment by laszlocsomor** [comment]
Ping @laurentlb , what's the status of this bug?

**Comment by laszlocsomor** [comment]
Ah never mind, just saw the referenced PR.

**Comment by laszlocsomor** [comment]
Verified that it's fixed now:

```
  $ git remote -vv
origin  https://github.com/google/protobuf (fetch)
origin  https://github.com/google/protobuf (push)

  $ git rev-parse HEAD
31c54d1289f2ae44158eff631526762366ba1707

  $ bazel build //:protobuf_test
(...)
INFO: Build completed successfully, 513 total actions
```
