### ISSUE TITLE
'shared_mutex' is unavailable: introduced in macOS 10.12

### ISSUE THREAD

**Issue by 4kangjc** [bazelbuild/bazel#23194]
### Description of the bug:

Compilation succeeds with bazel-6, but fails with bazel-7
test.cc:3:24: error: 'shared_mutex' is unavailable: introduced in macOS 10.12
using SinkMutex = std::shared_mutex;

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`BUILD.bazel`
``` python
cc_binary(
    name = "test",
    srcs = ["test.cc"],
    copts = ["-std=c++17"],
)
```
`test.cc`
```cpp
#include <shared_mutex>

using SinkMutex = std::shared_mutex;

int main() {}
```

### Which operating system are you running Bazel on?

MacOS 14.5

### What is the output of `bazel info release`?

Starting local Bazel server and connecting to it... release 7.1.2-homebrew

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

$./bazelisk-darwin-arm64 --bisect=6.5.0..7.0.0 build ...
first bad commit is https://github.com/bazelbuild/bazel/commit/d56dc18e1978102e35fbcf92c5d63f9f9eef37cd

**Comment by comius** [comment]
Please report the issue in rules_apple. cc @keith

**Comment by keith** [comment]
On bazel 7.x if you'd like the apple specific toolchain you should set it up with these instructions https://github.com/bazelbuild/apple_support#toolchain-setup

Otherwise you can pass the `--macos_minimum_os` and `--host_macos_minimum_os` flags to make sure you're targeting what you'd expect

**Comment by 4kangjc** [comment]
> On bazel 7.x if you'd like the apple specific toolchain you should set it up with these instructions https://github.com/bazelbuild/apple_support#toolchain-setup
> 
> Otherwise you can pass the `--macos_minimum_os` and `--host_macos_minimum_os` flags to make sure you're targeting what you'd expect

I followed https://github.com/bazelbuild/apple_support?tab=readme-ov-file#bazel-7-setup and added `bazel_dep(name = "apple_support", version = "1.16.0", repo_name = "build_bazel_apple_support")` in MOUDLE.bazel, but got the following error:
![image](https://github.com/user-attachments/assets/7ae7f39a-fe51-46c4-9a37-3ad56a0f130e)

**Comment by keith** [comment]
see https://github.com/bazelbuild/bazel/issues/23111 for that error

note that this toolchain requires xcode, if the issue is because you don't have that installed and don't want to, you'll have to try the other flags i mentioned

**Comment by 4kangjc** [comment]
> see #23111 for that error
> 
> note that this toolchain requires xcode, if the issue is because you don't have that installed and don't want to, you'll have to try the other flags i mentioned

Ok，thanks
