### ISSUE TITLE
Release - November 2017 - Target RC date: 2017-11-06 - name: 0.8.0

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3772]
Release tracking bug for november 2017:

* Target cut: November, 6th -- during the Bazel Conference

* Name: 0.8.0

/cc @dslomov. I should be the RM for this one but I would gladly exchange with yours in December seeing that I will be at the repro build summit.

**Comment by dslomov** [comment]
I can be an RM for this one. How about we cut on Mon Nov. 6 (I can cut while at the summit)

**Comment by dslomov** [comment]
I plan to cut at cff0dc94f6a8e16492adf54c88d0b26abe903d4c
Nightly looks good: https://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/nightly/109/

**Comment by damienmg** [comment]
Sounds good I'll let you know if the one remaining issue is genuine

**Comment by davido** [comment]
What about this https://github.com/bazelbuild/bazel/issues/3965?

**Comment by damienmg** [comment]
We do not have CI coverage for it, which means you will have to check with
the release candidate and report regression. Cc @meteorcloudy.

Technically since this was not working on 0.7, this would not be a
regression. Testing those is hard however. Anyway if you can test the
proposed baseline and tell us if that works before we cut the RC that would
probably be the best.

**Comment by katre** [comment]
Dmitry, platforms documentation was just submitted internally. Can we get
it into the release?

**Comment by davido** [comment]
@damienmg @meteorcloudy 

Trying to build gerrit master with bazel master is failing for me on Windows now, with:

```
$ bazel build --workspace_status_command=tools/workspace-status.cmd headless
Loading:
Loading: 0 packages loaded
INFO: Analysed target //:headless (0 packages loaded).
INFO: Found 1 target...
[0 / 14] BazelWorkspaceStatusAction stable-status.txt
ERROR: C:/users/davido/projects/gerrit/java/gerrit/BUILD:1:1: Building java/gerrit/libprolog-predicates.jar (19 source files) failed (Exit 1)
java\gerrit\PRED_commit_edits_2.java:99: error: incompatible types: ImmutableList cannot be converted to List<Edit>
          List<Edit> edits = entry.getEdits();
                                           ^
Target //:headless failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

This happens here on most recent Java 8 version:

```
$ "$JAVA_HOME/bin/javac" -version
javac 1.8.0_152
```

It seems that [ths diff fixed it](http://paste.openstack.org/show/625563/): 

```
$ bazel build --workspace_status_command=tools/workspace-status.cmd headless
Loading:
Loading: 0 packages loaded
INFO: Analysed target //:headless (0 packages loaded).
INFO: Found 1 target...
[0 / 9] BazelWorkspaceStatusAction stable-status.txt
Target //:headless up-to-date:
  C:/msys64/tmp/_bazel_davido/_biltsqa/execroot/gerrit/bazel-out/x64_windows-fastbuild/bin/headless.war
INFO: Elapsed time: 1,868s, Critical Path: 0,76s
INFO: Build completed successfully, 3 total actions
```

**Comment by damienmg** [comment]
So do you mean the problem is on gerrit side?

**Comment by davido** [comment]
I believe, this is a JDK bug. A workaround can be provided on gerrit site. I also checked, that the same problem exists in Bazel 0.7 already. It's not clear to me why this problem does not exist on sane platforms (Linux * Mac Os X).

**Comment by dslomov** [comment]
I cut with `devtools/blaze/bazel/admin/release.sh create 0.8.0 cff0dc9`

**Comment by aj-michael** [comment]
please cherry pick internal change 174503874 which has been submitted but not exported yet, its a release blocker that would break Android AAR support (internal bug 68858732) /cc @jin

**Comment by dslomov** [comment]
Internal change 174503874 is https://github.com/bazelbuild/bazel/commit/8a49b156c4edf710e3e1e0acfde5a8d27cc3a086, cherry-picking

**Comment by dslomov** [comment]
rc2: `devtools/blaze/bazel/admin/release.sh create 0.8.0 cff0dc9 8a49b15`

**Comment by petemounce** [comment]
https://chocolatey.org/packages/bazel/0.8.0-rc2 is up.

**Comment by meteorcloudy** [comment]
We need to cherry-pick e28d3af92227cd60287d27d9efa7593ae3e0509f for fixing https://github.com/bazelbuild/bazel/issues/3927

**Comment by meteorcloudy** [comment]
Also https://github.com/bazelbuild/bazel/issues/3956 is still under investigation, https://github.com/bazelbuild/bazel/commit/4869c4e17d5b1410070a1570f3244148d8f97b5d might need to be rollbacked.

**Comment by dslomov** [comment]
e28d3af is already in the release, no need to cherrypick

**Comment by meteorcloudy** [comment]
Good to know, thanks!

**Comment by meteorcloudy** [comment]
Please cherry-pick 275ae45b1228bdd0f912c4fbd634b29ba4180383 to fix #3956

**Comment by dslomov** [comment]
275ae45 fails to apply cleanly, and after I fix merge conflicts, `scripts/release.sh` fails to detect that it needs to create rc3 (it creates rc1 instead). I will not be able to investigate until Friday.

**Comment by dslomov** [comment]
Got it, `scripts/release/release.sh` relies on local state

**Comment by dslomov** [comment]
rc3: `scripts/release/release.sh create --force_rc=3 0.8.0 cff0dc9 8a49b15 275ae45`

**Comment by dslomov** [comment]
recreated rc3 with the same command since I botcher conflict resolution

**Comment by dslomov** [comment]
3rd time's the charm

**Comment by meteorcloudy** [comment]
Great, thanks! I don't see #3956 happen again in 0.8.0rc3.

**Comment by dslomov** [comment]
Will need one more cherry-pick: fix for https://github.com/bazelbuild/bazel/issues/4035

**Comment by meteorcloudy** [comment]
We also have a cc_proto_library  regression in 0.7.0 on WIndows https://github.com/bazelbuild/bazel/issues/3985
Sent https://bazel-review.googlesource.com/#/c/bazel/+/21790/ to fix it.

**Comment by dslomov** [comment]
ok, waiting for both of those to land before cutting rc4

**Comment by dslomov** [comment]
One cherry-pick has landed (fix for #4035) https://github.com/bazelbuild/bazel/commit/d0bf589f2716b3d139c210930371a684c6e158eb
Waiting on a fix for #3985

**Comment by meteorcloudy** [comment]
The fix for #3985 just laded, https://github.com/bazelbuild/bazel/commit/9738f35abddb7ef7a7ef314b5d2a52a3be1b830a

**Comment by dslomov** [comment]
rc4: ` scripts/release/release.sh create 0.8.0 cff0dc9 8a49b15 275ae45 d0bf589 9738f35`

**Comment by damienmg** [comment]
We need to cherry-pick cl/176654245

**Comment by dslomov** [comment]
кс5Ж `scripts/release/release.sh create --force_rc=5 0.8.0 cff0dc9 8a49b15 275ae45 d0bf589 9738f35 0d6ff47`

**Comment by davido** [comment]
Should this release be blocked, untill #4108 is fixed?

**Comment by damienmg** [comment]
Not a regression so no.

**Comment by dslomov** [comment]
rc5 promoted to release

**Comment by petemounce** [comment]
https://chocolatey.org/packages/bazel/0.8.0 is live.

**Comment by dslomov** [comment]
Homebrew PR: https://github.com/Homebrew/homebrew-core/pull/21106

**Comment by Capstan** [comment]
Unfortunately, I think https://github.com/bazelbuild/bazel/issues/4173 is a regression.

**Comment by davido** [comment]
Bazel 0.8.0 native package for Alpine Linux is here: https://github.com/davido/bazel-alpine-package/releases/tag/0.8.0.
