### ISSUE TITLE
TF Android build are broken by 0.4.5rc1 on macOS

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2601]
Discussion with @yifeif who tested our RC with TF:
"upgraded android to the latest, it worked with bazel 0.4.2, but failed with 0.4.5rc1 https://ci.tensorflow.org/job/tensorflow-cl-android/17541/consoleFull"

Extract of the CI:
```
ERROR: /workspace/tensorflow/examples/android/BUILD:22:1: Linking of rule '//tensorflow/examples/android:libtensorflow_demo.so' failed: Process exited with status 1 [sandboxed].
/usr/local/google/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/unwind-dw2-fde-dip.c:461: error: undefined reference to 'dl_iterate_phdr'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Use --strategy=CppLink=standalone to disable sandboxing for the failing actions.
____Building complete.
Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
____Elapsed time: 43.471s, Critical Path: 30.92s
```

Other important point: they upgraded to NDK13, related?

/cc @aj-michael @ahumesky 
/cc @hermione521 another release blocker.

**Comment by aj-michael** [comment]
When was the release cut? Support for NDK13 is pretty new, I added it in 3809e4cdf2b540ff617a7cc347b5dafe98c84dfb,

**Comment by aj-michael** [comment]
Nevermind, I see that 3809e4c is in 0.4.5rc1. This looks like a bug in our ndk13 crosstool. Sadly we don't have very good coverage of ndk builds. I'm taking a look.

**Comment by aj-michael** [comment]
I've confirmed that their build still works* with NDK12.

\* They need to update the `build_tools_version` for `android_sdk_repository` in their `WORKSPACE` file to >= 24.0.3. Or, preferrably, just remove `build_tools_version` from their `WORKSPACE` since it has been optional since bazel 0.4.4.

**Comment by damienmg** [comment]
Actually the change updated it to 25.0.1, added you in CC. Maybe they are doing something wrong on their CI about it. Since it is not breaking with NDK12, I think we can remove it from release blocker.

**Comment by aj-michael** [comment]
Ah, I did not see their change that updates the build tools version. I was basing my claim on my local testing based on the tensorflow github master branch.

**Comment by aj-michael** [comment]
As an update, I tried NDK11 and NDK12 with our clang crosstool, and both of those builds failed.

**Comment by yifeif** [comment]
I have not tried android builds with upgraded tool and sdk version, NDK12 and 0.4.5rc1 bazel yet. Trying it right now.

**Comment by aj-michael** [comment]
I found the root of the problem: the ndk clang crosstool is settings gcc-specific system include paths. This is a problem in for all previous NDKs, not just 13, but NDK13 changed the default to clang.
