### ISSUE TITLE
[MSYS2] Executing genrule @protobuf//:generate_js_well_known_types_embed failed

### ISSUE THREAD

**Issue by Carmezim** [bazelbuild/bazel#2742]
Windows 10 x64
Msys2 v20160205
Bazel at HEAD (51b3a08e926d24c294b63b7354af77a9bfe8df67)
Visual C++ 2015

Error building TensorFlow

```
Adriano@Adriano MSYS /c/tensorflow
$ export BUILD_OPTS='--cpu=x64_windows_msvc --host_cpu=x64_windows_msvc --copt=/w --verbose_failures --experimental_ui'

Adriano@Adriano MSYS /c/tensorflow
$ bazel build -c opt $BUILD_OPTS --config=win-cuda //tensorflow/tools/pip_package:build_pip_package
WARNING: C:/tensorflow/tensorflow/workspace.bzl:30:5:
Current Bazel is not a release version, cannot check for compatibility.
WARNING: C:/tensorflow/tensorflow/workspace.bzl:31:5: Make sure that you are running at least Bazel 0.4.5.
INFO: Analysed target //tensorflow/tools/pip_package:build_pip_package.
INFO: Found 1 target...
ERROR: C:/tools/msys64/tmp/_bazel_adriano/x1e5egqw/external/protobuf/BUILD:247:1: Executing genrule @protobuf//:generate_js_well_known_types_embed failed: bash.exe failed: error executing command
  cd C:/tools/msys64/tmp/_bazel_adriano/x1e5egqw/execroot/tensorflow
  SET PATH=C:\tools\msys64\usr\bin;C:\tools\msys64\bin;C:\tools\msys64\usr\bin;C:\Users\Adriano\AppData\Local\Programs\Python\Python35\;C:\bazel\;c;C:\tools\msys64\Program Files\Java\jdk1.8.0_112\;C:\tools\msys64\home\Adriano\cmake-3.6.2-win32-x86\bin\;C:\tools\msys64\usr\local\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\opt\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\tools\msys64\usr\bin\site_perl;C:\tools\msys64\usr\bin\vendor_perl;C:\tools\msys64\usr\bin\core_perl;.
  C:/tools/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/external/protobuf/js_embed.exe external/protobuf/src/google/protobuf/compiler/js/well_known_types/any.js external/protobuf/src/google/protobuf/compiler/js/well_known_types/struct.js external/protobuf/src/google/protobuf/compiler/js/well_known_types/timestamp.js > bazel-out/host/genfiles/external/protobuf/src/google/protobuf/compiler/js/well_known_types_embed.cc: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 126
/usr/bin/bash: bazel-out/host/bin/external/protobuf/js_embed.exe: cannot execute binary file: Exec format error
ERROR: C:/tools/msys64/tmp/_bazel_adriano/x1e5egqw/external/gif_archive/BUILD.bazel:37:1: declared output 'external/gif_archive/windows/unistd.h' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 52.573s, Critical Path: 0.30s
FAILED: Build did NOT complete successfully

```

Steps to reproduce:
- Build bazel from source
- Build TensorFlow with generated binary on MSYS2

**Comment by philwo** [comment]
Hi @Carmezim,

could you please check and post the output of the following?

ls -l bazel-out/host/bin/external/protobuf/js_embed.exe
file bazel-out/host/bin/external/protobuf/js_embed.exe

I'm curious why that file cannot be executed and gives an "Exec format error".

**Comment by Carmezim** [comment]
Sure
```
$ ls -l bazel-out/host/bin/external/protobuf/js_embed.exe
-r-xr-xr-x 1 Adriano Adriano 2097152 Mar 27 10:58 bazel-out/host/bin/external/protobuf/js_embed.exe

$ file bazel-out/host/bin/external/protobuf/js_embed.exe
bazel-out/host/bin/external/protobuf/js_embed.exe: data

```

**Comment by philwo** [comment]
@laszlocsomor It looks like this build somehow generated a non-executable exe file, which "file" only recognizes as "data". :|

@Carmezim If you don't mind, could you attach the js_embed.exe file to this bug report? I really wonder what it is, if it's not a valid exe file.

**Comment by Carmezim** [comment]
There you go
[js_embed.zip](https://github.com/bazelbuild/bazel/files/872701/js_embed.zip)

**Comment by philwo** [comment]
The js_embed.exe consists of 2097152 bytes that all have the value 0. I don't know what happened there. Personally, I've also seen the MSYS compilers sometimes generate empty files as outputs...

If you delete it and just "bazel build" again, it should work. Obviously this shouldn't happen, we'll have to stress test Bazel on Windows a lot more to catch and fix all these bugs.

**Comment by Carmezim** [comment]
MSYS doesn't seem really robust and reliable as you pointed out. I will test as instructed and can update you if all goes fine. 
Thanks!

**Comment by Carmezim** [comment]
I was building on a new TF clone and got this error now

```
ERROR: C:/tools/msys64/tmp/_bazel_adriano/piryq3n9/external/llvm/BUILD:183:1: Executing genrule @llvm//:abi_breaking_gen failed: bash.exe failed: error executing command
  cd C:/tools/msys64/tmp/_bazel_adriano/piryq3n9/execroot/tensorflow
  SET PATH=C:\tools\msys64\usr\bin;C:\tools\msys64\bin;C:\tools\msys64\usr\bin;C:\Users\Adriano\AppData\Local\Programs\Python\Python35\;C:\bazel\;c;C:\tools\msys64\Program Files\Java\jdk1.8.0_112\;C:\tools\msys64\home\Adriano\cmake-3.6.2-win32-x86\bin\;C:\tools\msys64\usr\local\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\opt\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\tools\msys64\usr\bin\site_perl;C:\tools\msys64\usr\bin\vendor_perl;C:\tools\msys64\usr\bin\core_perl;.
  C:/tools/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/third_party/llvm/expand_cmake_vars "HAVE_DIRENT_H=1" "HAVE_DLFCN_H=1" "HAVE_ERRNO_H=1" "HAVE_EXECINFO_H=1" "HAVE_FCNTL_H=1" "HAVE_INTTYPES_H=1" "HAVE_PTHREAD_H=1" "HAVE_SIGNAL_H=1" "HAVE_STDINT_H=1" "HAVE_SYS_IOCTL_H=1" "HAVE_SYS_MMAN_H=1" "HAVE_SYS_PARAM_H=1" "HAVE_SYS_RESOURCE_H=1" "HAVE_SYS_STAT_H=1" "HAVE_SYS_TIME_H=1" "HAVE_SYS_TYPES_H=1" "HAVE_TERMIOS_H=1" "HAVE_UNISTD_H=1" "HAVE_ZLIB_H=1" "HAVE_BACKTRACE=1" "HAVE_DLOPEN=1" "HAVE_FUTIMES=1" "HAVE_GETCWD=1" "HAVE_GETPAGESIZE=1" "HAVE_GETRLIMIT=1" "HAVE_GETRUSAGE=1" "HAVE_GETTIMEOFDAY=1" "HAVE_INT64_T=1" "HAVE_ISATTY=1" "HAVE_LIBEDIT=1" "HAVE_LIBPTHREAD=1" "HAVE_LIBZ=1" "HAVE_MKDTEMP=1" "HAVE_MKSTEMP=1" "HAVE_MKTEMP=1" "HAVE_PREAD=1" "HAVE_PTHREAD_GETSPECIFIC=1" "HAVE_PTHREAD_MUTEX_LOCK=1" "HAVE_PTHREAD_RWLOCK_INIT=1" "HAVE_REALPATH=1" "HAVE_SBRK=1" "HAVE_SETENV=1" "HAVE_SETRLIMIT=1" "HAVE_SIGALTSTACK=1" "HAVE_STRERROR=1" "HAVE_STRERROR_R=1" "HAVE_STRTOLL=1" "HAVE_SYSCONF=1" "HAVE_UINT64_T=1" "HAVE__UNWIND_BACKTRACE=1" "ENABLE_BACKTRACES=1" "LLVM_BINDIR=/dev/null" "LLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING=0" "LLVM_ENABLE_ABI_BREAKING_CHECKS=0" "LLVM_ENABLE_THREADS=1" "LLVM_ENABLE_ZLIB=1" "LLVM_HAS_ATOMICS=1" "LLVM_INCLUDEDIR=/dev/null" "LLVM_INFODIR=/dev/null" "LLVM_MANDIR=/dev/null" "LLVM_NATIVE_TARGET=1" "LLVM_NATIVE_TARGETINFO=1" "LLVM_NATIVE_TARGETMC=1" "LLVM_NATIVE_ASMPRINTER=1" "LLVM_NATIVE_ASMPARSER=1" "LLVM_NATIVE_DISASSEMBLER=1" "LLVM_ON_UNIX=1" "LLVM_PREFIX=/dev/null" "LLVM_VERSION_MAJOR=0" "LLVM_VERSION_MINOR=0" "LLVM_VERSION_PATCH=0" "LTDL_SHLIB_EXT=.so" "PACKAGE_NAME=llvm" "PACKAGE_STRING=llvm tensorflow-trunk" "PACKAGE_VERSION=tensorflow-trunk" "RETSIGTYPE=void" "LLVM_HOST_TRIPLE=x86_64-unknown-linux_gnu" "LLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-linux_gnu" "LLVM_NATIVE_ARCH=X86" "HAVE_MALLOC_H=1" "HAVE_LINK_H=1" "HAVE_MALLINFO=1" "HAVE_FUTIMENS=1"< external/llvm/include/llvm/Config/abi-breaking.h.cmake > bazel-out/host/genfiles/external/llvm/include/llvm/Config/abi-breaking.h: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1
Traceback (most recent call last):
  File "C:\Users\Adriano\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Adriano\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "bazel-out\host\bin\third_party\llvm\expand_cmake_vars\__main__.py", line 173, in <module>
  File "bazel-out\host\bin\third_party\llvm\expand_cmake_vars\__main__.py", line 153, in Main
AssertionError: Could not find python binary: python3.exe
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 194.868s, Critical Path: 22.57s
FAILED: Build did NOT complete successfully

```

**Comment by philwo** [comment]
@meteorcloudy FYI

**Comment by meteorcloudy** [comment]
Hi @Carmezim , I don't know how to fix "Exec format error" as well.

But for `AssertionError: Could not find python binary: python3.exe`, I noticed Bazel doesn't take `python3_path` for host build when specifying `--host_python_force_python=py3`.

Can you delete `--host_python_force_python=py3`, and rerun the build again?

**Comment by laszlocsomor** [comment]
I'm bumping this to P1. Sounds like we may have a correctness issue here if we indeed generate corrupt output files. We need to investigate whether it's a problem with bazel or with the compiler/linker. And this time it was the MSVC toolchain; i've only seen the rare corrupt output with GCC.

**Comment by meteorcloudy** [comment]
@laszlocsomor Yeah, sounds like a P1 to me as well.

@Carmezim I just filed https://github.com/bazelbuild/bazel/issues/2752 for the python3 error.

**Comment by Carmezim** [comment]
@meteorcloudy  here is the log after deleting `--host_python_force_python=py3` from `bazelrc`
```
$ bazel build -c opt $BUILD_OPTS --config=win-cuda //tensorflow/tools/pip_package:build_pip_package
WARNING: C:/users/adriano/documents/tensorflow/tensorflow/workspace.bzl:30:5:
Current Bazel is not a release version, cannot check for compatibility.
WARNING: C:/users/adriano/documents/tensorflow/tensorflow/workspace.bzl:31:5: Make sure that you are running at least Bazel 0.4.5.
INFO: Analysed target //tensorflow/tools/pip_package:build_pip_package.
INFO: Found 1 target...
INFO: From Linking external/protobuf/python/google/protobuf/internal/_api_implementation.so:
   Creating library bazel-out/msvc_x64-py3-opt/bin/external/protobuf/python/google/protobuf/internal/_api_implementation.lib and object bazel-out/msvc_x64-py3-opt/bin/external/protobuf/python/google/protobuf/internal/_api_implementation.exp
INFO: From Compiling external/swig/Source/Modules/allocate.cxx [for host]:
allocate.cxx
INFO: From Compiling external/swig/Source/Modules/swigmain-lite.cxx [for host]:
swigmain-lite.cxx
INFO: From Compiling external/swig/Source/Modules/overload.cxx [for host]:
overload.cxx
INFO: From Compiling external/swig/Source/Modules/contract.cxx [for host]:
contract.cxx
INFO: From Compiling external/swig/Source/Modules/module.cxx [for host]:
module.cxx
INFO: From Compiling external/swig/Source/Modules/main.cxx [for host]:
main.cxx
INFO: From Compiling external/swig/Source/Modules/typepass.cxx [for host]:
typepass.cxx
INFO: From Compiling external/swig/Source/Modules/emit.cxx [for host]:
emit.cxx
INFO: From Compiling external/swig/Source/Modules/xml.cxx [for host]:
xml.cxx
INFO: From Compiling external/swig/Source/Modules/utils.cxx [for host]:
utils.cxx
INFO: From Compiling external/swig/Source/Modules/directors.cxx [for host]:
directors.cxx
INFO: From Compiling external/swig/Source/Modules/nested.cxx [for host]:
nested.cxx
INFO: From Compiling external/swig/Source/Modules/lang.cxx [for host]:
lang.cxx
INFO: From Compiling external/swig/Source/Modules/uffi.cxx [for host]:
uffi.cxx
INFO: From Compiling external/swig/Source/Modules/browser.cxx [for host]:
browser.cxx
INFO: From Compiling external/swig/Source/Modules/python.cxx [for host]:
python.cxx
INFO: From Compiling tensorflow/core/util/version_info.cc [for host]:
Warning: Unmatched arguments: -fno-exceptions -msse3
INFO: From Linking external/swig/swig.exe [for host]:
misc.o : warning LNK4217: locally defined symbol pcre_compile imported in function Swig_string_regex
naming.o : warning LNK4217: locally defined symbol pcre_compile imported in function Swig_name_object_get
misc.o : warning LNK4217: locally defined symbol pcre_exec imported in function Swig_string_regex
naming.o : warning LNK4217: locally defined symbol pcre_exec imported in function Swig_name_object_get
misc.o : warning LNK4217: locally defined symbol pcre_version imported in function Swig_pcre_version
misc.o : warning LNK4217: locally defined symbol pcre_free imported in function Swig_string_regex
naming.o : warning LNK4049: locally defined symbol pcre_free imported
INFO: From Compiling external/com_googlesource_code_re2/re2/stringpiece.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/filtered_re2.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/prog.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/prefilter_tree.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/dfa.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/bitstate.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/simplify.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/regexp.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/util/rune.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/tostring.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/mimics_pcre.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/re2.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/prefilter.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/unicode_groups.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/perl_groups.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/parse.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/set.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/unicode_casefold.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/nfa.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/onepass.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/re2/compile.cc [for host]:
Warning: Unmatched arguments: -pthread
INFO: From Compiling external/com_googlesource_code_re2/util/strutil.cc [for host]:
Warning: Unmatched arguments: -pthread
ERROR: C:/tools/msys64/tmp/_bazel_adriano/piryq3n9/external/llvm/BUILD:1667:1: C++ compilation of rule '@llvm//:support' failed: msvc_cl.bat failed: error executing command
  cd C:/tools/msys64/tmp/_bazel_adriano/piryq3n9/execroot/tensorflow
  SET PATH=external/local_config_cc/wrapper/bin
    SET PWD=/proc/self/cwd
  external/local_config_cc/wrapper/bin/msvc_cl.bat -m64 /D__inline__=__inline /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAGMA_SUPPORTED /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /D_USE_MATH_DEFINES /nologo /bigobj /Zm500 /J /Gy /GF /W3 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /DNDEBUG /O2 -Xcompilation-mode=opt /w -DLLVM_ENABLE_STATS -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D_DEBUG -DLLVM_BUILD_GLOBAL_ISEL /Iexternal/llvm /Ibazel-out/msvc_x64-py3-opt/genfiles/external/llvm /Iexternal/bazel_tools /Ibazel-out/msvc_x64-py3-opt/genfiles/external/bazel_tools /Iexternal/zlib_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/zlib_archive /Iexternal/llvm/include /Ibazel-out/msvc_x64-py3-opt/genfiles/external/llvm/include /Iexternal/bazel_tools/tools/cpp/gcc3 /Iexternal/zlib_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/zlib_archive /DEPENDENCY_FILE bazel-out/msvc_x64-py3-opt/bin/external/llvm/_objs/support/external/llvm/lib/Support/GraphWriter.d /c external/llvm/lib/Support/GraphWriter.cpp /Fobazel-out/msvc_x64-py3-opt/bin/external/llvm/_objs/support/external/llvm/lib/Support/GraphWriter.o: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 2
external/llvm/include\llvm/Support/Host.h(25): fatal error C1083: Cannot open include file: 'machine/endian.h': No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 599.248s, Critical Path: 58.31s
FAILED: Build did NOT complete successfully

```

**Comment by meteorcloudy** [comment]
@Carmezim I filed a separate issue for TF GPU build, please check https://github.com/bazelbuild/bazel/issues/2753

**Comment by laszlocsomor** [comment]
We believe this bug was caused by #2774. Stay tuned for a fix soon!
