### ISSUE TITLE
TensorFlow is failing with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#3347]
```
ERROR: C:/jenkins/workspace/tensorflow/bazel_version/head/platform_name/windows-x86_64/tensorflow/core/BUILD:1242:1: C++ compilation of rule '//tensorflow/core:lib_internal' failed (Exit 2): msvc_cl.bat failed: error executing command 
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\\shared;C:\Program Files (x86)\Windows Kits\8.1\include\\um;C:\Program Files (x86)\Windows Kits\8.1\include\\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;c:\tools\cuda\bin;c:\program files\nvidia gpu computing toolkit\cuda\v8.0\extras\cupti\libx64;c:\program files\nvidia gpu computing toolkit\cuda\v8.0\bin;c:\program files\anaconda3\scripts;c:\program files\anaconda3;c:\tools\msys64\usr\local\bin;c:\tools\msys64\usr\bin;c:\tools\msys64\usr\bin;c:\tools\msys64\opt\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\tools\msys64\usr\bin\site_perl;c:\tools\msys64\usr\bin\vendor_perl;c:\tools\msys64\usr\bin\core_perl;C:\windows\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Program Files/Anaconda3/python.exe
    SET PYTHON_LIB_PATH=C:/Program Files/Anaconda3/lib/site-packages
    SET TEMP=c:\tools\msys64\tmp
    SET TF_NEED_CUDA=0
    SET TF_NEED_OPENCL=0
    SET TMP=c:\tools\msys64\tmp
  external/local_config_cc/wrapper/bin/msvc_cl.bat /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 -Xcompilation-mode=opt -w /nologo /I. /Ibazel-out/msvc_x64-py3-opt/genfiles /Iexternal/bazel_tools /Ibazel-out/msvc_x64-py3-opt/genfiles/external/bazel_tools /Iexternal/protobuf /Ibazel-out/msvc_x64-py3-opt/genfiles/external/protobuf /Iexternal/eigen_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/eigen_archive /Iexternal/local_config_sycl /Ibazel-out/msvc_x64-py3-opt/genfiles/external/local_config_sycl /Iexternal/gif_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/gif_archive /Iexternal/jpeg /Ibazel-out/msvc_x64-py3-opt/genfiles/external/jpeg /Iexternal/com_googlesource_code_re2 /Ibazel-out/msvc_x64-py3-opt/genfiles/external/com_googlesource_code_re2 /Iexternal/farmhash_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/farmhash_archive /Iexternal/fft2d /Ibazel-out/msvc_x64-py3-opt/genfiles/external/fft2d /Iexternal/highwayhash /Ibazel-out/msvc_x64-py3-opt/genfiles/external/highwayhash /Iexternal/png_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/png_archive /Iexternal/zlib_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/zlib_archive /Iexternal/snappy /Ibazel-out/msvc_x64-py3-opt/genfiles/external/snappy /Iexternal/bazel_tools/tools/cpp/gcc3 /Iexternal/protobuf/src /Ibazel-out/msvc_x64-py3-opt/genfiles/external/protobuf/src /Iexternal/eigen_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/eigen_archive /Iexternal/gif_archive/lib /Ibazel-out/msvc_x64-py3-opt/genfiles/external/gif_archive/lib /Iexternal/gif_archive/windows /Ibazel-out/msvc_x64-py3-opt/genfiles/external/gif_archive/windows /Iexternal/farmhash_archive/src /Ibazel-out/msvc_x64-py3-opt/genfiles/external/farmhash_archive/src /Iexternal/png_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/png_archive /Iexternal/zlib_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/zlib_archive /showIncludes /MT /O2 /c tensorflow/core/lib/random/simple_philox.cc /Fobazel-out/msvc_x64-py3-opt/bin/tensorflow/core/_objs/lib_internal/tensorflow/core/lib/random/simple_philox.o -msse3 /DLANG_CXX11 /D__VERSION__="MSVC" /DPLATFORM_WINDOWS /DTF_COMPILE_LIBRARY /DEIGEN_HAS_C99_MATH /DTENSORFLOW_USE_EIGEN_THREADPOOL /DEIGEN_AVOID_STL_ARRAY /Iexternal/gemmlowp /wd4018 /U_HAS_EXCEPTIONS /D_HAS_EXCEPTIONS=1 /EHsc
.\tensorflow/core/platform/default/logging.h(228): error C2589: '(': illegal token on right side of '::'
.\tensorflow/core/platform/default/logging.h(228): error C2059: syntax error: '::'
.\tensorflow/core/platform/default/logging.h(228): error C2143: syntax error: missing ';' before '{'
.\tensorflow/core/platform/default/logging.h(229): error C2589: '(': illegal token on right side of '::'
.\tensorflow/core/platform/default/logging.h(229): error C2059: syntax error: '::'
.\tensorflow/core/platform/default/logging.h(229): error C2143: syntax error: missing ';' before '{'
.\tensorflow/core/platform/default/logging.h(230): error C2589: '(': illegal token on right side of '::'
.\tensorflow/core/platform/default/logging.h(230): error C2059: syntax error: '::'
.\tensorflow/core/platform/default/logging.h(230): error C2143: syntax error: missing ';' before '{'
.\tensorflow/core/platform/default/logging.h(231): error C2589: '(': illegal token on right side of '::'
.\tensorflow/core/platform/default/logging.h(231): error C2059: syntax error: '::'
.\tensorflow/core/platform/default/logging.h(231): error C2143: syntax error: missing ';' before '{'
.\tensorflow/core/platform/default/logging.h(232): error C2589: '(': illegal token on right side of '::'
.\tensorflow/core/platform/default/logging.h(232): error C2059: syntax error: '::'
.\tensorflow/core/platform/default/logging.h(232): error C2143: syntax error: missing ';' before '{'
.\tensorflow/core/platform/default/logging.h(233): error C2589: '(': illegal token on right side of '::'
.\tensorflow/core/platform/default/logging.h(233): error C2059: syntax error: '::'
.\tensorflow/core/platform/default/logging.h(233): error C2143: syntax error: missing ';' before '{'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 157.273s, Critical Path: 60.08s
```

It's caused by 87250d979d3622bc3fdb6095799a668841a2b152 where we removed `/DNOMINMAX`.
I'll send a PR to TF to fix this.
Latest is also failing because of a test error, already filed issue https://github.com/tensorflow/tensorflow/issues/11345
FYI, @laszlocsomor

**Comment by meteorcloudy** [comment]
Wait.. `/DNOMINMAX` looks like a very common use, I think it's better to add it back to CROSSTOOL.
