### ISSUE TITLE
Bazel fails to build on MacOS Sonoma 14.1 and XCode 15.0.1

### ISSUE THREAD

**Issue by rsalvador** [bazelbuild/bazel#20076]
### Description of the bug:

I upgraded to MacOS 14.1 and XCode 15.0.1 and the bazel source fails to build:
```
$ bazel build //src:bazel
...
In file included from external/abseil-cpp~20220623.1/absl/strings/str_join.h:59:
In file included from external/abseil-cpp~20220623.1/absl/strings/internal/str_join_internal.h:42:
In file included from external/abseil-cpp~20220623.1/absl/strings/internal/resize_uninitialized.h:26:
external/abseil-cpp~20220623.1/absl/meta/type_traits.h:560:8: error: builtin __has_trivial_assign is deprecated; use __is_trivially_assignable instead [-Werror,-Wdeprecated-builtins]
      (__has_trivial_assign(ExtentsRemoved) || !kIsCopyOrMoveAssignable) &&
       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Error in child process '/usr/bin/xcrun'. 1
Target //src:bazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 44.987s, Critical Path: 4.87s
INFO: 125 processes: 67 internal, 58 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

### Which category does this issue belong to?

Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Clone https://github.com/bazelbuild/bazel and try to build on MacOS Sonoma 14.1

### Which operating system are you running Bazel on?

MacOS 14.1

### What is the output of `bazel info release`?

release 6.4.0

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
c30826dc83aedb7f726ef0e4a16be092559bdead
```

### Have you found anything relevant by searching the web?

I tried `bazel sync --configure` and `bazel clean --expunge` but neither fixed the problem.

**Comment by keith** [comment]
quick workaround is `--copt=-Wno-deprecated-builtins --host_copt=-Wno-deprecated-builtins`

**Comment by sgowroji** [comment]
Hi @rsalvador, Did you get a chance to try the above [comment](https://github.com/bazelbuild/bazel/issues/20076#issuecomment-1799082618) and resolve it?  Thanks!

**Comment by rsalvador** [comment]
Yes, it builds with the workaround.

**Comment by keith** [comment]
The solution is likely to update the libraries in the errors to new versions that have fixed the warnings

**Comment by meteorcloudy** [comment]
I tried to upgrade abseil-cpp, but it seems to introduce some unnecessary dependencies: https://github.com/bazelbuild/bazel-central-registry/pull/847/files#r1341120148

**Comment by meteorcloudy** [comment]
@bazel-io fork 7.0.0

**Comment by meteorcloudy** [comment]
I'm sending a fix and hopefully I can backport it to 7.0.0 today.
