### ISSUE TITLE
com.sun.management.ThreadMXBean#getCurrentThreadAllocatedBytes() is missing in remote JDK 11

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#13323]
If I install recent Open JDK 11 on Linux or Mac Os X, the method is there: `getCurrentThreadAllocatedBytes`:

```
  $ java -fullversion
  openjdk full version "11.0.10+9-suse-1.2-x8664"
```

And the method is there:

```java
  $ javap com.sun.management.ThreadMXBean
Compiled from "ThreadMXBean.java"
public interface com.sun.management.ThreadMXBean extends java.lang.management.ThreadMXBean {
  public abstract long[] getThreadCpuTime(long[]);
  public abstract long[] getThreadUserTime(long[]);
  public default long getCurrentThreadAllocatedBytes();
  public abstract long getThreadAllocatedBytes(long);
  public abstract long[] getThreadAllocatedBytes(long[]);
  public abstract boolean isThreadAllocatedMemorySupported();
  public abstract boolean isThreadAllocatedMemoryEnabled();
  public abstract void setThreadAllocatedMemoryEnabled(boolean);
}
```

If I try to build with Bazel 4.0.0 a class that is trying to use this method: [1], the build will fail:

```
  $ bazel build java/com/google/gerrit/metrics/...
  [...]
  java/com/google/gerrit/metrics/proc/ThreadMXBeanSun.java:38: error: cannot find symbol
    return sys.getCurrentThreadAllocatedBytes();
              ^
  symbol:   method getCurrentThreadAllocatedBytes()
  location: variable sys of type ThreadMXBean
INFO: Elapsed time: 4.435s, Critical Path: 4.32s
INFO: 4 processes: 1 remote cache hit, 2 internal, 1 linux-sandbox.
FAILED: Build did NOT complete successfully
```

And in fact, with javap of provided remote JDK 11:

```
  $ /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/remotejdk11_linux/bin/java -fullversion
openjdk full version "11.0.6+10-LTS"
```

We can confirm that this method is missing:

```
  $ /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/remotejdk11_linux/bin/javap com.s
un.management.ThreadMXBean
Compiled from "ThreadMXBean.java"
public interface com.sun.management.ThreadMXBean extends java.lang.management.ThreadMXBean {
  public abstract long[] getThreadCpuTime(long[]);
  public abstract long[] getThreadUserTime(long[]);
  public abstract long getThreadAllocatedBytes(long);
  public abstract long[] getThreadAllocatedBytes(long[]);
  public abstract boolean isThreadAllocatedMemorySupported();
  public abstract boolean isThreadAllocatedMemoryEnabled();
  public abstract void setThreadAllocatedMemoryEnabled(boolean);
}
```

Even though, the method is documented: [2].

Workaround: To use another method: `getThreadAllocatedBytes` that is provided in remote JDK 11:

```java
@Override
  public long getCurrentThreadAllocatedBytes() {
    // TODO(ms): call getCurrentThreadAllocatedBytes as soon as this is available in the patched
    // Java version used by bazel
    return sys.getThreadAllocatedBytes(Thread.currentThread().getId());
  }
```

[1] https://gerrit-review.googlesource.com/c/gerrit/+/301213/8/java/com/google/gerrit/metrics/proc/ThreadMXBeanSun.java#38
[2] https://docs.oracle.com/en/java/javase/11/docs/api/jdk.management/com/sun/management/ThreadMXBean.html#getCurrentThreadAllocatedBytes()

**Comment by comius** [comment]
Interesting, so we should upgrade remote jdk 11, but there were problems with android support. See https://github.com/bazelbuild/bazel/issues/12880.

@davido, what command line options did you use? Without any options Bazel should only compile using remotejdk11, and use system libraries of locally installed JDK. That is it should see the missing method if you have JDK with it in the JAVA_HOME.

**Comment by davido** [comment]
@comius 

Thanks for looking into it.

This is the patch on gerrit@HEAD to reproduce the issue:

```diff
diff --git a/java/com/google/gerrit/metrics/proc/ThreadMXBeanSun.java b/java/com/google/gerrit/metrics/proc/ThreadMXBeanSun.java
index 9e43a057ca..ff39e77a7f 100644
--- a/java/com/google/gerrit/metrics/proc/ThreadMXBeanSun.java
+++ b/java/com/google/gerrit/metrics/proc/ThreadMXBeanSun.java
@@ -37,6 +37,7 @@ class ThreadMXBeanSun implements ThreadMXBeanInterface {
   public long getCurrentThreadAllocatedBytes() {
     // TODO(ms): call getCurrentThreadAllocatedBytes as soon as this is available in the patched
     // Java version used by bazel
-    return sys.getThreadAllocatedBytes(Thread.currentThread().getId());
+    //return sys.getThreadAllocatedBytes(Thread.currentThread().getId());
+    return sys.getCurrentThreadAllocatedBytes());
   }
 }
```

Moreover, on gerrit@HEAD, we added `--announce_rc` option:

```
$ bazelisk build java/com/google/gerrit/metrics/
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 975e8af1-d12d-4414-a01e-5fb0bd9aaeb9
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=141
INFO: Reading rc options for 'build' from /home/davido/projects/gerrit/.bazelrc:
  'build' options: --workspace_status_command=python3 ./tools/workspace_status.py --repository_cache=~/.gerritcodereview/bazel-cache/repository --action_env=PATH --disk_cache=~/.gerritcodereview/bazel-cache/cas --java_toolchain=//tools:error_prone_warnings_toolchain_java11 --incompatible_strict_action_env --announce_rc --experimental_worker_multiplex=false
INFO: Reading rc options for 'build' from /home/davido/.bazelrc:
  'build' options: --experimental_generate_json_trace_profile --experimental_profile_cpu_usage
ERROR: Skipping 'java/com/google/gerrit/metrics/': The package part of 'java/com/google/gerrit/metrics/' should not end in a slash
WARNING: Target pattern parsing failed.
ERROR: The package part of 'java/com/google/gerrit/metrics/' should not end in a slash
INFO: Elapsed time: 4.789s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

As can be seen, we are using custom toolchain: `--java_toolchain=//tools:error_prone_warnings_toolchain_java11` to activate additional Error Prone check.

This is defined as the following:

```python
default_java_toolchain(
    name = "error_prone_warnings_toolchain",
    bootclasspath = ["@bazel_tools//tools/jdk:platformclasspath.jar"],
    jvm_opts = JDK9_JVM_OPTS,
    package_configuration = [
        ":error_prone",
    ],
    visibility = ["//visibility:public"],
)

JDK11_JVM_OPTS = select({
    "@bazel_tools//src/conditions:openbsd": ["-Xbootclasspath/p:$(location @bazel_tools//tools/jdk:javac_jar)"],
    "//conditions:default": [
        "--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED",
        "--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED",
        "--add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED",
        "--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED",
        "--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED",
        "--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED",
        "--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED",
        "--add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED",
        "--patch-module=java.compiler=$(location @bazel_tools//tools/jdk:java_compiler_jar)",
        "--patch-module=jdk.compiler=$(location @bazel_tools//tools/jdk:jdk_compiler_jar)",
        "--add-opens=java.base/java.nio=ALL-UNNAMED",
        "--add-opens=java.base/java.lang=ALL-UNNAMED",
    ],
})

default_java_toolchain(
    name = "error_prone_warnings_toolchain_java11",
    bootclasspath = ["@bazel_tools//tools/jdk:platformclasspath.jar"],
    forcibly_disable_header_compilation = False,
    genclass = ["@bazel_tools//tools/jdk:genclass"],
    header_compiler = ["@bazel_tools//tools/jdk:turbine"],
    header_compiler_direct = ["@bazel_tools//tools/jdk:turbine_direct"],
    ijar = ["@bazel_tools//tools/jdk:ijar"],
    javabuilder = ["@bazel_tools//tools/jdk:javabuilder"],
    javac_supports_workers = True,
    jvm_opts = JDK11_JVM_OPTS,
    misc = [
        "-XDskipDuplicateBridges=true",
        "-g",
        "-parameters",
    ],
    package_configuration = [
        ":error_prone",
    ],
    singlejar = ["@bazel_tools//tools/jdk:singlejar"],
    source_version = "11",
    target_version = "11",
    tools = [
        "@bazel_tools//tools/jdk:java_compiler_jar",
        "@bazel_tools//tools/jdk:javac_jar",
        "@bazel_tools//tools/jdk:jdk_compiler_jar",
    ],
    visibility = ["//visibility:public"],
)

# Error Prone errors enabled by default; see ../.bazelrc for how this is
# enabled. This warnings list is originally based on:
# https://github.com/bazelbuild/BUILD_file_generator/blob/master/tools/bazel_defs/java.bzl
# However, feel free to add any additional errors. Thus far they have all been pretty useful.
# TODO(davido): Enable ImmutableAnnotationChecker again when these issues are fixed:
# https://github.com/google/error-prone/issues/1348
# https://github.com/bazelbuild/bazel/issues/9378
java_package_configuration(
    name = "error_prone",
    javacopts = [
        "-XepDisableWarningsInGeneratedCode",
        "-Xep:AmbiguousMethodReference:ERROR",
        "-Xep:AutoValueFinalMethods:ERROR",
        "-Xep:BadAnnotationImplementation:ERROR",
        "-Xep:BadComparable:ERROR",
        "-Xep:BoxedPrimitiveConstructor:ERROR",
        "-Xep:CannotMockFinalClass:ERROR",
        "-Xep:ClassCanBeStatic:ERROR",
        "-Xep:ClassNewInstance:ERROR",
        "-Xep:DateFormatConstant:ERROR",
        "-Xep:DefaultCharset:ERROR",
        "-Xep:DoubleCheckedLocking:ERROR",
        "-Xep:ElementsCountedInLoop:ERROR",
        "-Xep:EqualsHashCode:ERROR",
        "-Xep:EqualsIncompatibleType:ERROR",
        "-Xep:ExpectedExceptionChecker:ERROR",
        "-Xep:Finally:ERROR",
        "-Xep:FloatingPointLiteralPrecision:ERROR",
        "-Xep:FormatStringAnnotation:ERROR",
        "-Xep:FragmentInjection:ERROR",
        "-Xep:FragmentNotInstantiable:ERROR",
        "-Xep:FunctionalInterfaceClash:ERROR",
        "-Xep:FutureReturnValueIgnored:ERROR",
        "-Xep:GetClassOnEnum:ERROR",
        "-Xep:ImmutableAnnotationChecker:OFF",
        "-Xep:ImmutableEnumChecker:ERROR",
        "-Xep:IncompatibleModifiers:ERROR",
        "-Xep:InjectOnConstructorOfAbstractClass:ERROR",
        "-Xep:InputStreamSlowMultibyteRead:ERROR",
        "-Xep:IterableAndIterator:ERROR",
        "-Xep:JUnit3FloatingPointComparisonWithoutDelta:ERROR",
        "-Xep:JUnitAmbiguousTestClass:ERROR",
        "-Xep:LiteralClassName:ERROR",
        "-Xep:MissingCasesInEnumSwitch:ERROR",
        "-Xep:MissingFail:ERROR",
        "-Xep:MissingOverride:ERROR",
        "-Xep:MutableConstantField:ERROR",
        "-Xep:NarrowingCompoundAssignment:ERROR",
        "-Xep:NonAtomicVolatileUpdate:ERROR",
        "-Xep:NonOverridingEquals:ERROR",
        "-Xep:NullableConstructor:ERROR",
        "-Xep:NullablePrimitive:ERROR",
        "-Xep:NullableVoid:ERROR",
        "-Xep:ObjectToString:ERROR",
        "-Xep:OperatorPrecedence:ERROR",
        "-Xep:OverridesGuiceInjectableMethod:ERROR",
        "-Xep:PreconditionsInvalidPlaceholder:ERROR",
        "-Xep:ProtoFieldPreconditionsCheckNotNull:ERROR",
        "-Xep:ProtocolBufferOrdinal:ERROR",
        "-Xep:ReferenceEquality:ERROR",
        "-Xep:RequiredModifiers:ERROR",
        "-Xep:ShortCircuitBoolean:ERROR",
        "-Xep:SimpleDateFormatConstant:ERROR",
        "-Xep:StaticGuardedByInstance:ERROR",
        "-Xep:StringEquality:ERROR",
        "-Xep:SynchronizeOnNonFinalField:ERROR",
        "-Xep:TruthConstantAsserts:ERROR",
        "-Xep:TypeParameterShadowing:ERROR",
        "-Xep:TypeParameterUnusedInFormals:ERROR",
        "-Xep:URLEqualsHashCode:ERROR",
        "-Xep:UnsynchronizedOverridesSynchronized:ERROR",
        "-Xep:UnusedException:ERROR",
        "-Xep:WaitNotInLoop:ERROR",
        "-Xep:WildcardImport:ERROR",
    ],
    packages = ["error_prone_packages"],
)

package_group(
    name = "error_prone_packages",
    packages = [
        "//java/...",
        "//javatests/...",
        "//plugins/codemirror-editor/...",
        "//plugins/commit-message-length-validator/...",
        "//plugins/delete-project/...",
        "//plugins/download-commands/...",
        "//plugins/gitiles/...",
        "//plugins/hooks/...",
        "//plugins/plugin-manager/...",
        "//plugins/replication/...",
        "//plugins/reviewnotes/...",
        "//plugins/singleusergroup/...",
        "//plugins/webhooks/...",
    ],
)
```

**Comment by davido** [comment]
I have extracted two line reproducer: https://github.com/davido/bazel_mxbean.

BUILD
```python
java_library(
    name = "mxbean",
    srcs = ["java/ThreadMXBeanSun.java"],
)
```

and the Java file is:

```java
import com.sun.management.ThreadMXBean;

class ThreadMXBeanSun {
  private final ThreadMXBean sys;

  ThreadMXBeanSun(java.lang.management.ThreadMXBean sys) {
    this.sys = (ThreadMXBean) sys;
  }

  public long getCurrentThreadAllocatedBytes() {
    // TODO(ms): call getCurrentThreadAllocatedBytes as soon as this is available in the patched
    // Java version used by bazel
    //return sys.getThreadAllocatedBytes(Thread.currentThread().getId());
    return sys.getCurrentThreadAllocatedBytes();
  }
}
```

I can build this file with local Javac (JDK 11):

```
  $ javac java/ThreadMXBeanSun.java 
```

And it's failing to build with Bazel 4.0.0:

```
  $ bazelisk build :mxbean
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:mxbean (23 packages loaded, 437 targets configured).
INFO: Found 1 target...
ERROR: /home/davido/projects/bazel_mxbean/BUILD:1:13: Building libmxbean.jar (1 source file) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
java/ThreadMXBeanSun.java:14: error: cannot find symbol
    return sys.getCurrentThreadAllocatedBytes();
              ^
  symbol:   method getCurrentThreadAllocatedBytes()
  location: variable sys of type ThreadMXBean
Target //:mxbean failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 18.986s, Critical Path: 7.77s
INFO: 4 processes: 2 internal, 2 linux-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by davido** [comment]
I'm testing with this PR: https://github.com/bazelbuild/bazel/pull/12849.

**Comment by comius** [comment]
> Any chance, this PR can land ASAP?

I'll rebase PR: #12849 and downstream test it. I'm not aware of any fixes in Android, that caused the rollback https://github.com/bazelbuild/bazel/commit/e8f3e0f503a2f209a6e3b61911db44b3a03354dd, but let's see.

**Comment by comius** [comment]
> > Any chance, this PR can land ASAP?
> 
> I'll rebase PR: #12849 and downstream test it. I'm not aware of any fixes in Android, that caused the rollback [e8f3e0f](https://github.com/bazelbuild/bazel/commit/e8f3e0f503a2f209a6e3b61911db44b3a03354dd), but let's see.

Couldn't reopen PR, the new one is https://github.com/bazelbuild/bazel/pull/13444, but unfortunately Android issues are not fixed; so we can't upgrade.

**Comment by davido** [comment]
> Couldn't reopen PR, the new one is #13444, but unfortunately Android issues are not fixed; so we can't upgrade.

Thanks for looking into it!

**Comment by davido** [comment]
This was fixed in Bazel 5.0.0 release.
