### ISSUE TITLE
cc_library build failure with --all_incompatible_changes

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#7546]
### Description of the problem / feature request:

Building a `cc_library` while testing new deprecations with `--all_incompatible_changes` fails with bazel 0.23.0 (this also reproduces with HEAD @ 436135fb059bf9179ea06d923a2592bcb159036b)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Using this sample project: [cc_sample.zip](https://github.com/bazelbuild/bazel/files/2906704/cc_sample.zip)

Run:

```
% bazel build //:foo --all_incompatible_changes --incompatible_enable_cc_toolchain_resolution=false --verbose_failures
```

And you get this error:

```
INFO: Analysed target //:foo (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /private/tmp/cc_sample/BUILD:1:1: C++ compilation of rule '//:foo' failed (Exit 1) wrapped_clang failed: error executing command
  (cd /private/var/tmp/_bazel_ksmiley/087bedd255ee08b27be8e3f906d09a28/sandbox/darwin-sandbox/1/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.14 \
    PATH=/bin:/usr/bin \
    XCODE_VERSION_OVERRIDE=10.1.0 \
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG -isysroot __BAZEL_XCODE_SDKROOT__ '-mmacosx-version-min=10.14' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c main.c -o bazel-out/darwin-fastbuild/bin/_objs/foo/main.o)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox: wrapped_clang failed: error executing command
  (cd /private/var/tmp/_bazel_ksmiley/087bedd255ee08b27be8e3f906d09a28/sandbox/darwin-sandbox/1/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.14 \
    PATH=/bin:/usr/bin \
    XCODE_VERSION_OVERRIDE=10.1.0 \
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG -isysroot __BAZEL_XCODE_SDKROOT__ '-mmacosx-version-min=10.14' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c main.c -o bazel-out/darwin-fastbuild/bin/_objs/foo/main.o)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
main.c:1:10: fatal error: 'foo.h' file not found
#include "foo.h"
         ^~~~~~~
1 error generated.
Target //:foo failed to build
INFO: Elapsed time: 0.207s, Critical Path: 0.07s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

(the `--incompatible_enable_cc_toolchain_resolution=false` isn't intentionally part of this issue, although it may be related, but without that I get a failure that is fixed by https://github.com/bazelbuild/bazel/pull/7544)

The issue appears to be that the `includes` from the BUILD file aren't being passed with `-isystem` to clang.

### What operating system are you running Bazel on?

macOS 

### What's the output of `bazel info release`?

release 0.23.0rc3

**Comment by keith** [comment]
@hlopko is this the same issue as https://github.com/bazelbuild/bazel/issues/7550 ?

**Comment by hlopko** [comment]
Yup, `--all_incompatible_changes is just too optimistic that all our incompatible changes are ready to be migrated :) Sorry for the inconvenience.
