### ISSUE TITLE
python_stub_template: `AttributeError: 'module' object has no attribute 'OrderedDict'` on CentOS 6

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/bazel#11265]
### Description of the problem / feature request:

Recently upgraded to Bazel 3.1.0. Discovered that CentOS 6 users (don't ask) are now broken due to https://github.com/bazelbuild/bazel/commit/d5012a7ed19c1e75e413373fa22c5f1b08a9ee29.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Get yourself a Linux environment where `#!/usr/bin/env python` invokes Python 2.6.6.
1. Run any `py_binary`, such as rules_pkg's `build_tar`.

### What operating system are you running Bazel on?

CentOS 6.6

### What's the output of `bazel info release`?

`release 3.1.0-vmware`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

- https://github.com/bazelbuild/rules_python/blob/master/proposals/2018-11-08-customizing-the-python-stub-template.md acknowledges non-hermeticity.
- https://github.com/bazelbuild/bazel/issues/137 discusses support for customizable templates.

### Any other information, logs, or outputs that you want to share?

Non-hermeticity is the key problem for me. We have Python toolchains to decouple our builds from tools provided by the user's OS, but the stub's shebang bypasses these.

Workarounds I'm considering:
- Reverting d5012a7ed19c1e75e413373fa22c5f1b08a9ee29.
- Reimplementing in terms of Python 2.6.
- Tweaking the stub to begin with `%python_binary%` instead of `#!/usr/bin/env python`.

**Comment by beasleyr-vmw** [comment]
Closing since #11269 was merged. (Test [failure](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/ba8e8f6f-6aa7-4ba4-88ae-15b4adda44a5/src/test/java/com/google/devtools/build/lib/skyframe/SkyframeTests/attempt_1.log) appears to be unrelated.)
