### ISSUE TITLE
Bazel 0.5.3 doesn't work with Android build-tools 26.0.1

### ISSUE THREAD

**Issue by fishy** [bazelbuild/bazel#3469]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

If I use Android build-tools 26.0.1 to build an android_binary target, I got the following errors:

```
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexBuilder.java:20: error: cannot find symbol
import com.android.dx.command.DxConsole;
                             ^
  symbol:   class DxConsole
  location: package com.android.dx.command
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:18: error: cannot find symbol
import com.android.dx.command.DxConsole;
                             ^
  symbol:   class DxConsole
  location: package com.android.dx.command
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileMerger.java:22: error: cannot find symbol
import com.android.dx.command.DxConsole;
                             ^
  symbol:   class DxConsole
  location: package com.android.dx.command
```

It works in Android build-tools 25.0.3

### Environment info
* Operating System:
Tried on both macOS 10.12.6 and Debian with kernel 4.11.0-2-amd64

* Bazel version (output of `bazel info release`):
release 0.5.3-homebrew

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

Nah

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

This might be another Android build-tools release bug, or maybe Android build-tools 26 removed some feature that Bazel relied on.

**Comment by aj-michael** [comment]
:( I'll take a look shortly. For context, Bazel contains some tools that compile at Bazel runtime against the dx.jar in th end users android SDK.

@ahumesky, @kevin1e100 are you aware of any recent changes to dx?

**Comment by aj-michael** [comment]
There is nothing in the changelog that would have indicated this: https://developer.android.com/studio/releases/build-tools.html

**Comment by ahumesky** [comment]
Looks like it was deleted here:
https://android.googlesource.com/platform/dalvik/+/8f68769869e02895dc6474a5cd0bca20977e5ecd

**Comment by ahumesky** [comment]
It looks like a minor refactoring of the code, I wouldn't expect something like that to make it to release notes

**Comment by aj-michael** [comment]
WORKAROUND: Use the flag `--noincremental_dexing`. The error is in a tool which is used for a feature that was turned on by default in Bazel 0.5.3 (which coincidentally happened shortly before the 26.0.1 release).

**Comment by fishy** [comment]
I can confirm that the workaround works for me.

**Comment by buchgr** [comment]
@aj-michael are you working on a fix for 0.5.4?

**Comment by aj-michael** [comment]
@buchgr -- I have not started working on the fix. We had some internal discussion about a fix that would drop support for build-tools versions before 26.0.1 with @kevin1e100.

When will bazel 0.5.4 be cut? While this issue is severe, I don't think it is release blocking as we have a workaround and it only effects one build tools version so far.

**Comment by buchgr** [comment]
@aj-michael ok. we will cut 0.5.4 once we fixed our CI :-). ASAP.

**Comment by buchgr** [comment]
@aj-michael should this be cherry-picked? 0.5.4 is not released yet.

**Comment by aj-michael** [comment]
@buchgr, that would be nice. However, you would need to cherrypick both ce61d63 and 5393a49.

**Comment by huangl111** [comment]
@fishy How to Use the flag --noincremental_dexing in linux?

**Comment by aj-michael** [comment]
@huangl111 like this `blaze build --noincremental_dexing //my:app`
