### ISSUE TITLE
`@remote_java_tools` fail to build on macOS 13.3 with Xcode 14.3

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#17956]
### Description of the bug:

Building `@remote_java_tools` from source on macOS 13.3 with Xcode 14.3 fails with:

```
external/remote_java_tools/java_tools/zlib/gzlib.c:254:9: error: call to undeclared function 'lseek'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        LSEEK(state->fd, 0, SEEK_END);  /* so gzoffset() is correct */
        ^
external/remote_java_tools/java_tools/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
external/remote_java_tools/java_tools/zlib/gzlib.c:254:9: note: did you mean 'fseek'?
external/remote_java_tools/java_tools/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdio.h:162:6: note: 'fseek' declared here
int      fseek(FILE *, long, int);
         ^
external/remote_java_tools/java_tools/zlib/gzlib.c:260:24: error: call to undeclared function 'lseek'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        state->start = LSEEK(state->fd, 0, SEEK_CUR);
                       ^
external/remote_java_tools/java_tools/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
external/remote_java_tools/java_tools/zlib/gzlib.c:361:9: error: call to undeclared function 'lseek'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    if (LSEEK(state->fd, state->start, SEEK_SET) == -1)
        ^
external/remote_java_tools/java_tools/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
external/remote_java_tools/java_tools/zlib/gzlib.c:402:15: error: call to undeclared function 'lseek'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        ret = LSEEK(state->fd, offset - (z_off64_t)state->x.have, SEEK_CUR);
              ^
external/remote_java_tools/java_tools/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
external/remote_java_tools/java_tools/zlib/gzlib.c:498:14: error: call to undeclared function 'lseek'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    offset = LSEEK(state->fd, 0, SEEK_CUR);
             ^
external/remote_java_tools/java_tools/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
5 errors generated.
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to build a Java target on macOS 13.3 with Xcode 14.3 using a non-prebuilt Java toolchain such as:

```starlark
load("@bazel_tools//tools/jdk:default_java_toolchain.bzl", "NONPREBUILT_TOOLCHAIN_CONFIGURATION", "default_java_toolchain")
default_java_toolchain(
    name = "java_non_prebuilt",
    configuration = NONPREBUILT_TOOLCHAIN_CONFIGURATION,
)
```

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

6.1.1

### Have you found anything relevant by searching the web?

This does appear to be an unfixed portability issue in zlib.

Other repos apply patches to resolve this: https://github.com/Blosc/c-blosc/pull/353/commits/ac72c2cf8248c6fdfb8b1ed97e1da95f8714870f

### Any other information, logs, or outputs that you want to share?

This can be worked around with `--host_conlyopt=-std=c90` (see https://github.com/bazelbuild/bazel/issues/17956#issuecomment-1494853070 for less intrusive workarounds).

**Comment by adamjstewart** [comment]
I just encountered this issue as well. Is it possible to use an externally installed copy of zlib instead of relying on `third_party`?

**Comment by pjjw** [comment]
for anyone else who lands here, fixes are either adding `-std=c90` to the zlib BUILD file copts, or adding `build --per_file_copt='external/zlib/.*\.c@-std=c90' --host_per_file_copt='external/zlib/.*\.c@-std=c90'` to their .bazelrc

the blanket `--host_conlyopt=-std=c90` flag can break a lot of other common/important things, like the go compiler

**Comment by meteorcloudy** [comment]
@fmeum Does this also break building Bazel with the latest Xcode toolchain? (I'll also try to test it)

**Comment by fmeum** [comment]
@meteorcloudy I am only relaying this information from our devs on Macs, I don't have the setup to test this myself right now. I would think so though.

**Comment by meteorcloudy** [comment]
Yes, it broke bazel build as well.
```
$ bazel build //src:bazel
INFO: Invocation ID: 1a5a89d4-c183-49f4-bda0-6f569d4fb28f
INFO: Reading 'startup' options from /Users/pcloudy/.bazelrc: --host_jvm_args=-Djava.net.preferIPv6Addresses=true
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=331
INFO: Reading rc options for 'build' from /Users/pcloudy/workspace/bazel/.bazelrc:
  Inherited 'common' options: --enable_platform_specific_config
INFO: Reading rc options for 'build' from /Users/pcloudy/workspace/bazel/.bazelrc:
  'build' options: --java_language_version=11 --tool_java_language_version=11
INFO: Reading rc options for 'build' from /Users/pcloudy/.bazelrc:
  'build' options: --verbose_failures --announce_rc --disk_cache=/tmp/bazel_disk_cache --repository_cache=/tmp/bazel_repository_cache
INFO: Found applicable config definition build:macos in file /Users/pcloudy/workspace/bazel/.bazelrc: --macos_minimum_os=10.10
INFO: Analyzed target //src:bazel (335 packages loaded, 9877 targets configured).
INFO: Found 1 target...
ERROR: /Users/pcloudy/workspace/bazel/third_party/zlib/BUILD:39:19: Compiling third_party/zlib/gzwrite.c [for tool] failed: (Exit 1): wrapped_clang failed: error executing command (from target //third_party/zlib:zlib_checked_in)
  (cd /private/var/tmp/_bazel_pcloudy/829441223e9fec5a5a2e3d1dd743fdf0/sandbox/darwin-sandbox/15/execroot/io_bazel && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=13.3 \
    PATH=/Users/pcloudy/Library/Caches/bazelisk/downloads/bazelbuild/bazel-6.1.1-darwin-arm64/bin:/Users/pcloudy/bin/google-cloud-sdk/bin:/opt/homebrew/bin:/Users/pcloudy/bin:/usr/local/git/git-google/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin \
    XCODE_VERSION_OVERRIDE=14.3.0.14E222b \
    ZERO_AR_DATE=1 \
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG '-DNS_BLOCK_ASSERTIONS=1' 'DEBUG_PREFIX_MAP_PWD=.' -iquote . -iquote bazel-out/darwin_arm64-opt-exec-EDC14992/bin -isystem third_party/zlib -isystem bazel-out/darwin_arm64-opt-exec-EDC14992/bin/third_party/zlib -MD -MF bazel-out/darwin_arm64-opt-exec-EDC14992/bin/third_party/zlib/_objs/zlib_checked_in/gzwrite.d '-DBAZEL_CURRENT_REPOSITORY=""' '-frandom-seed=bazel-out/darwin_arm64-opt-exec-EDC14992/bin/third_party/zlib/_objs/zlib_checked_in/gzwrite.o' -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-canonical-prefixes -pthread -g0 -w '-Dverbose=-1' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -target arm64-apple-macosx13.3 -c third_party/zlib/gzwrite.c -o bazel-out/darwin_arm64-opt-exec-EDC14992/bin/third_party/zlib/_objs/zlib_checked_in/gzwrite.o)
# Configuration: e8ff020b2b067b6b6ee8bdda4e7996c46b822986011eca4b767411efb47daa7f
# Execution platform: //:default_host_platform

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
third_party/zlib/gzwrite.c:89:20: error: call to undeclared function 'write'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            writ = write(state->fd, strm->next_in, put);
                   ^
third_party/zlib/gzwrite.c:89:20: note: did you mean 'fwrite'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdio.h:165:9: note: 'fwrite' declared here
size_t   fwrite(const void * __restrict __ptr, size_t __size, size_t __nitems, FILE * __restrict __stream) __DARWIN_ALIAS(fwrite);
         ^
third_party/zlib/gzwrite.c:119:24: error: call to undeclared function 'write'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                writ = write(state->fd, state->x.next, put);
                       ^
third_party/zlib/gzwrite.c:673:9: error: call to undeclared function 'close'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    if (close(state->fd) == -1)
        ^
3 errors generated.
Error in child process '/usr/bin/xcrun'. 1
```

@hvadehra I'll fix zlib in the Bazel repo first, then will hand it over to you to have a new java tools release.

**Comment by fmeum** [comment]
@meteorcloudy If there will be a 5.4.1 release, maybe the fix for this should be included in that release as well?

**Comment by meteorcloudy** [comment]
@fmeum Oh, that makes sense, how confident are we that Blosc/c-blosc@ac72c2c  is the correct fix, it's weird I don't see any upstream issue or PR mentioning this problem.

@brentleyjones Yes, looks like the same error.

**Comment by meteorcloudy** [comment]
@kshyanashree @keertk We should also cherry pick the fix for this issue into 5.4.1

**Comment by meteorcloudy** [comment]
@bazel-io fork 5.4.1

**Comment by meteorcloudy** [comment]
@bazel-io fork 6.2.0

**Comment by fmeum** [comment]
> @fmeum Oh, that makes sense, how confident are we that [Blosc/c-blosc@ac72c2c](https://github.com/Blosc/c-blosc/commit/ac72c2c) is the correct fix, it's weird I don't see any upstream issue or PR mentioning this problem.

`gzlib.c` doesn't seem to transitively include `unistd.h`, but still uses either `lseek` or `lseek64` [here](https://github.com/madler/zlib/blob/04f42ceca40f73e2978b50e93806c2a18c1281fc/gzlib.c#L8-L16). I am also surprised that this hasn't come up in many more places though.

**Comment by meteorcloudy** [comment]
I noticed the BCR zlib wasn't affected because it has `-DZ_HAVE_UNISTD_H`, I guess in the zlib CMake build, they have similar setup.
https://github.com/bazelbuild/bazel-central-registry/blob/d539ffc39452332ade4910910eadfc9fbce200bf/modules/zlib/1.2.13/patches/add_build_file.patch#L42

**Comment by jameslan** [comment]
Will there be a 6.1.2 to include this fix? We are using 6.1.1. 6.2 is scheduled for June, that's 2 months to go.

**Comment by kshyanashree** [comment]
Hi @jameslan! As of now there's no 6.1.2 planned. We will keep you informed in any further updates. Thanks!

**Comment by casian** [comment]
Hi is it possible to apply this patch to version 4.2.0? Thanks

**Comment by keertk** [comment]
@jameslan @casian we're working on patch releases 6.1.2 and 4.2.4 - progress can be tracked in https://github.com/bazelbuild/bazel/issues/18031 and https://github.com/bazelbuild/bazel/issues/18033 respectively.

**Comment by keertk** [comment]
@bazel-io fork 4.2.4

**Comment by keertk** [comment]
@bazel-io fork 6.1.2

**Comment by meteorcloudy** [comment]
For fixing `remote_java_tools` itself, we'll need a separate java_tools release. /cc @hvadehra can you do that?

**Comment by meteorcloudy** [comment]
@hvadehra After having the new release, do we need to upgrade the java_tools version embedded in Bazel?

**Comment by hvadehra** [comment]
> @hvadehra After having the new release, do we need to upgrade the java_tools version embedded in Bazel?

I think only for the non-prebuilt java toolchain case.

**Comment by meteorcloudy** [comment]
@hvadehra I see, can you follow up with a fix and some cherry picks?

**Comment by hvadehra** [comment]
I'm thinking we make a new java_tools release at HEAD and cherry-pick embedding that into 6.2. If waiting for 6.2 is not possible, one can override the java_tools version in WORKSPACE. @meteorcloudy WDYT?

**Comment by meteorcloudy** [comment]
> one can override the java_tools version in WORKSPACE

I guess that should be fine? Can you give some instruction here on how to do that?

Given the limited impact and the existing workaround with `--host_conlyopt=-std=c90`, probably no additional cherry pick for the patch releases are needed. /cc @keertk

**Comment by hvadehra** [comment]
> I guess that should be fine? Can you give some instruction here on how to do that?

The instructions are published with every java_tools release, eg: https://github.com/bazelbuild/java_tools/releases/tag/java_v12.0

@keertk @kshyanashree  Would it be possible for you to make a regular release for java_tools? I'm going to be OOO soon and might not be able to finish the process.

**Comment by keertk** [comment]
Sure, we can do the release. Tracked here: https://github.com/bazelbuild/java_tools/issues/69

**Comment by casian** [comment]
> [4.2.4] `@remote_java_tools` fail to build on macOS 13.3 with Xcode 14.3 #18034

Thanks! Much appreciated!!

**Comment by keertk** [comment]
java_tools v12.1 + instructions: https://github.com/bazelbuild/java_tools/releases/tag/java_v12.1
Will cherrypick into 6.2 as well.

cc @hvadehra @meteorcloudy @comius

**Comment by ShuizhuLin** [comment]
> 

I still encounter error by wrote 6.2.0 version to .bazelversion, but success after wrote the `"-std=c90"` to  java_tools/zlib/BUILD.bazel copts.
