### ISSUE TITLE
Bazel 1.0.0rc2 broke Gerrit (stable-2.14 release)

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#9353]
_Originally posted by @davido in https://github.com/bazelbuild/bazel/issues/8573#issuecomment-529503057_:

> It seems, that 1.0.0rc2 broke Gerrit (stable-2.14 release):
> 
> ```
>   ERROR: /home/jenkins/workspace/Gerrit-verifier-bazel/gerrit/gerrit-extension-api/BUILD:63:1: in java_doc rule //gerrit-extension-api:extension-api-javadoc: 
> Traceback (most recent call last):
> 	File "/home/jenkins/workspace/Gerrit-verifier-bazel/gerrit/gerrit-extension-api/BUILD", line 63
> 		java_doc(name = 'extension-api-javadoc')
> 	File "/home/jenkins/workspace/Gerrit-verifier-bazel/gerrit/tools/bzl/javadoc.bzl", line 20, in _impl
> 		depset(transitive = [j.java.transitive_...])
> 	File "/home/jenkins/workspace/Gerrit-verifier-bazel/gerrit/tools/bzl/javadoc.bzl", line 20, in depset
> 		j.java.transitive_deps
> object of type 'JavaSkylarkApiProvider' has no field 'transitive_deps'
> ```
> 
> It seems to be related to: [1]. This is the place in the code: [2]. This is the complete CI log: [3].
> 
> All is fine on 0.29.0 release.
> 
> [1] #7598
> [2] https://github.com/GerritCodeReview/gerrit/blob/stable-2.14/tools/bzl/javadoc.bzl#L20-L21
> [3] https://gerrit-ci.gerritforge.com/job/Gerrit-verifier-bazel/71542/consoleText

**Comment by laurentlb** [comment]
Did it work with Bazel 0.29 with `--incompatible_disallow_legacy_java_provider`?

**Comment by iirina** [comment]
According to https://gerrit-review.googlesource.com/c/gerrit/+/234724 there were some targets that were not built on Bazel's Gerrit CI and this failure wasn't caught when building with `--incompatible_disallow_legacy_java_provider`. @davido added the missing target in https://github.com/bazelbuild/continuous-integration/pull/815. 

The next step is migrating `gerrit/tools/bzl/javadoc.bzl` as well.

**Comment by davido** [comment]
@laurentlb @iirina Thanks you for helping out with the migration. The fix is here: [1].

* [1] https://gerrit-review.googlesource.com/c/gerrit/+/236272

**Comment by davido** [comment]
The fix was merged. This issue can be closed.
