### ISSUE TITLE
[7.0.0rc1]/Bazel@HEAD regression: protobuf tests are failing with runtime mismatch

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#19890]
### Description of the bug:

After bumping of Bazel to 7.0.0rc1 our `protobuf` junit tests are failing:

```
  $> bazeldev test //javatests/com/google/gerrit/proto:proto_tests
[...]
There were 3 failures:
1) parseUncheckedByteArrayWrongProtoType(com.google.gerrit.proto.ProtosTest)
java.lang.AssertionError: expected java.lang.IllegalArgumentException but java.lang.NoSuchMethodError was thrown
	at com.google.gerrit.testing.GerritJUnit.assertThrows(GerritJUnit.java:49)
	at com.google.gerrit.proto.ProtosTest.parseUncheckedByteArrayWrongProtoType(ProtosTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:108)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:116)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:145)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:76)
Caused by: java.lang.NoSuchMethodError: 'boolean com.google.protobuf.GeneratedMessageV3$Builder.parseUnknownField(com.google.protobuf.CodedInputStream, com.google.protobuf.ExtensionRegistryLite, int)'
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$ChangeColumnsProto$Builder.mergeFrom(Cache.java:5563)
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$ChangeColumnsProto$Builder.mergeFrom(Cache.java:5171)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:872)
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$Builder.mergeFrom(Cache.java:12133)
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$1.parsePartialFrom(Cache.java:16285)
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$1.parsePartialFrom(Cache.java:16277)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$1.parseFrom(Cache.java:16277)
	at com.google.gerrit.proto.Protos.parseUnchecked(Protos.java:79)
	at com.google.gerrit.proto.ProtosTest.lambda$parseUncheckedByteArrayWrongProtoType$0(ProtosTest.java:38)
	at com.google.gerrit.testing.GerritJUnit.assertThrows(GerritJUnit.java:42)
	... 32 more
2) parseUncheckedSegmentOfByteArrayWrongProtoType(com.google.gerrit.proto.ProtosTest)
java.lang.AssertionError: expected java.lang.IllegalArgumentException but java.lang.NoSuchMethodError was thrown
	at com.google.gerrit.testing.GerritJUnit.assertThrows(GerritJUnit.java:49)
	at com.google.gerrit.proto.ProtosTest.parseUncheckedSegmentOfByteArrayWrongProtoType(ProtosTest.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:108)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:116)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:145)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:76)
Caused by: java.lang.NoSuchMethodError: 'boolean com.google.protobuf.GeneratedMessageV3$Builder.parseUnknownField(com.google.protobuf.CodedInputStream, com.google.protobuf.ExtensionRegistryLite, int)'
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$ChangeColumnsProto$Builder.mergeFrom(Cache.java:5563)
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$ChangeColumnsProto$Builder.mergeFrom(Cache.java:5171)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:872)
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$Builder.mergeFrom(Cache.java:12133)
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$1.parsePartialFrom(Cache.java:16285)
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$1.parsePartialFrom(Cache.java:16277)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:197)
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$1.parseFrom(Cache.java:16277)
	at com.google.gerrit.proto.Protos.parseUnchecked(Protos.java:97)
	at com.google.gerrit.proto.ProtosTest.lambda$parseUncheckedSegmentOfByteArrayWrongProtoType$2(ProtosTest.java:72)
	at com.google.gerrit.testing.GerritJUnit.assertThrows(GerritJUnit.java:42)
	... 32 more
3) parseUncheckedByteStringWrongProtoType(com.google.gerrit.proto.ProtosTest)
java.lang.AssertionError: expected java.lang.IllegalArgumentException but java.lang.NoSuchMethodError was thrown
	at com.google.gerrit.testing.GerritJUnit.assertThrows(GerritJUnit.java:49)
	at com.google.gerrit.proto.ProtosTest.parseUncheckedByteStringWrongProtoType(ProtosTest.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:108)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:116)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:145)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:76)
Caused by: java.lang.NoSuchMethodError: 'boolean com.google.protobuf.GeneratedMessageV3$Builder.parseUnknownField(com.google.protobuf.CodedInputStream, com.google.protobuf.ExtensionRegistryLite, int)'
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$ChangeColumnsProto$Builder.mergeFrom(Cache.java:5563)
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$ChangeColumnsProto$Builder.mergeFrom(Cache.java:5171)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:872)
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$Builder.mergeFrom(Cache.java:12133)
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$1.parsePartialFrom(Cache.java:16285)
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$1.parsePartialFrom(Cache.java:16277)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:100)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:120)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:125)
	at com.google.gerrit.server.cache.proto.Cache$ChangeNotesStateProto$1.parseFrom(Cache.java:16277)
	at com.google.gerrit.proto.Protos.parseUnchecked(Protos.java:112)
	at com.google.gerrit.proto.ProtosTest.lambda$parseUncheckedByteStringWrongProtoType$4(ProtosTest.java:115)
	at com.google.gerrit.testing.GerritJUnit.assertThrows(GerritJUnit.java:42)
	... 32 more

FAILURES!!!
Tests run: 9,  Failures: 3

WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by com.google.testing.junit.runner.util.GoogleTestSecurityManager (file:/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/rules_java~6.3.1~toolchains~remote_java_tools/java_tools/Runner_deploy.jar)
WARNING: Please consider reporting this to the maintainers of com.google.testing.junit.runner.util.GoogleTestSecurityManager
WARNING: System::setSecurityManager will be removed in a future release

BazelTestRunner exiting with a return value of 1
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2023-10-19 09:33:54 --

================================================================================
INFO: Found 1 test target...
Target //javatests/com/google/gerrit/proto:proto_tests up-to-date:
  bazel-bin/javatests/com/google/gerrit/proto/proto_tests
  bazel-bin/javatests/com/google/gerrit/proto/proto_tests.jar
INFO: Elapsed time: 5.516s, Critical Path: 5.01s
INFO: 27 processes: 18 disk cache hit, 5 internal, 2 linux-sandbox, 2 worker.
INFO: Build completed, 1 test FAILED, 27 total actions
//javatests/com/google/gerrit/proto:proto_tests                          FAILED in 0.6s
```

We are currently using outdated `protobuf` version:

WORKSPACE
```python
[...]
http_archive(
    name = "com_google_protobuf",
    sha256 = "3bd7828aa5af4b13b99c191e8b1e884ebfa9ad371b0ce264605d347f135d2568",
    strip_prefix = "protobuf-3.19.4",
    urls = [
        "https://github.com/protocolbuffers/protobuf/archive/v3.19.4.tar.gz",
    ],
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

[Clone](https://gerrit.googlesource.com/gerrit/) Gerrit Code Review recursively, and run:

```bash
  $> bazeldev test //javatests/com/google/gerrit/proto:proto_tests
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

Bazel@HEAD or 7.0.0rc1

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

```bazelisk build src:bazel-bin-dev```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

I am bisecting it right now, and will report later.

### Have you found anything relevant by searching the web?

https://github.com/protocolbuffers/protobuf/issues/10695

### Any other information, logs, or outputs that you want to share?

If I bump `protobuf` version to the same version used by Bazel, it seems to work also with Bazel@HEAD:

```diff
diff --git a/WORKSPACE b/WORKSPACE
index 5f50f21b69..dd66d64ba9 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -64,10 +64,10 @@ http_archive(
 
 http_archive(
     name = "com_google_protobuf",
-    sha256 = "3bd7828aa5af4b13b99c191e8b1e884ebfa9ad371b0ce264605d347f135d2568",
-    strip_prefix = "protobuf-3.19.4",
+    sha256 = "75be42bd736f4df6d702a0e4e4d30de9ee40eac024c4b845d17ae4cc831fe4ae",
+    strip_prefix = "protobuf-21.7",
     urls = [
-        "https://github.com/protocolbuffers/protobuf/archive/v3.19.4.tar.gz",
+        "https://github.com/protocolbuffers/protobuf/archive/v21.7.tar.gz",
     ],
 )
```

**Comment by fmeum** [comment]
Have you disabled Bzlmod with `--noenable_bzlmod`?

**Comment by davido** [comment]
@fmeum, Good point, I missed https://github.com/bazelbuild/bazel/issues/18958.

After adding this option, the test is failing to compile, while `guava` seems to be missing, after adding it the tests succeeds:

```diff
diff --git a/.bazelrc b/.bazelrc
index 3a412d45ad..6b09c5a308 100644
--- a/.bazelrc
+++ b/.bazelrc
@@ -1,3 +1,4 @@
+build --noenable_bzlmod
 build --workspace_status_command="python3 ./tools/workspace_status.py"
 build --repository_cache=~/.gerritcodereview/bazel-cache/repository
 build --action_env=PATH
diff --git a/javatests/com/google/gerrit/proto/BUILD b/javatests/com/google/gerrit/proto/BUILD
index 216ef942d8..381582afaf 100644
--- a/javatests/com/google/gerrit/proto/BUILD
+++ b/javatests/com/google/gerrit/proto/BUILD
@@ -7,6 +7,7 @@ junit_tests(
         "//java/com/google/gerrit/proto",
         "//java/com/google/gerrit/testing:gerrit-junit",
+       "//lib:guava",
         "//lib:protobuf",
         "//lib/truth",
         "//lib/truth:truth-proto-extension",
         "//proto:cache_java_proto",
```

**Comment by fmeum** [comment]
This is expected, earlier versions of Bazel leaked Guava in the classpath, which was fixed for 7.

**Comment by davido** [comment]
@fmeum Thanks for pointing me to tre tight direction.
